/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BuildingPreviousOperation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T01:19:29.594938500-03:00[America/Fortaleza]", comments = "Generator version: 7.19.0")
public class BuildingPreviousOperation {
  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  @javax.annotation.Nullable
  private String target;

  public static final String SERIALIZED_NAME_PRODUCTION = "production";
  @SerializedName(SERIALIZED_NAME_PRODUCTION)
  @javax.annotation.Nullable
  private String production;

  public static final String SERIALIZED_NAME_TURNS = "turns";
  @SerializedName(SERIALIZED_NAME_TURNS)
  @javax.annotation.Nullable
  private BigDecimal turns;

  public BuildingPreviousOperation() {
  }

  public BuildingPreviousOperation target(@javax.annotation.Nullable String target) {
    this.target = target;
    return this;
  }

  /**
   * Get target
   * @return target
   */
  @javax.annotation.Nullable
  public String getTarget() {
    return target;
  }

  public void setTarget(@javax.annotation.Nullable String target) {
    this.target = target;
  }


  public BuildingPreviousOperation production(@javax.annotation.Nullable String production) {
    this.production = production;
    return this;
  }

  /**
   * Get production
   * @return production
   */
  @javax.annotation.Nullable
  public String getProduction() {
    return production;
  }

  public void setProduction(@javax.annotation.Nullable String production) {
    this.production = production;
  }


  public BuildingPreviousOperation turns(@javax.annotation.Nullable BigDecimal turns) {
    this.turns = turns;
    return this;
  }

  /**
   * Get turns
   * @return turns
   */
  @javax.annotation.Nullable
  public BigDecimal getTurns() {
    return turns;
  }

  public void setTurns(@javax.annotation.Nullable BigDecimal turns) {
    this.turns = turns;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuildingPreviousOperation buildingPreviousOperation = (BuildingPreviousOperation) o;
    return Objects.equals(this.target, buildingPreviousOperation.target) &&
        Objects.equals(this.production, buildingPreviousOperation.production) &&
        Objects.equals(this.turns, buildingPreviousOperation.turns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(target, production, turns);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuildingPreviousOperation {\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    production: ").append(toIndentedString(production)).append("\n");
    sb.append("    turns: ").append(toIndentedString(turns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("target", "production", "turns"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BuildingPreviousOperation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BuildingPreviousOperation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BuildingPreviousOperation is not found in the empty JSON string", BuildingPreviousOperation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BuildingPreviousOperation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BuildingPreviousOperation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("target") != null && !jsonObj.get("target").isJsonNull()) && !jsonObj.get("target").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `target` to be a primitive type in the JSON string but got `%s`", jsonObj.get("target").toString()));
      }
      if ((jsonObj.get("production") != null && !jsonObj.get("production").isJsonNull()) && !jsonObj.get("production").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `production` to be a primitive type in the JSON string but got `%s`", jsonObj.get("production").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BuildingPreviousOperation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BuildingPreviousOperation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BuildingPreviousOperation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BuildingPreviousOperation.class));

       return (TypeAdapter<T>) new TypeAdapter<BuildingPreviousOperation>() {
           @Override
           public void write(JsonWriter out, BuildingPreviousOperation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BuildingPreviousOperation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BuildingPreviousOperation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BuildingPreviousOperation
   * @throws IOException if the JSON string is invalid with respect to BuildingPreviousOperation
   */
  public static BuildingPreviousOperation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BuildingPreviousOperation.class);
  }

  /**
   * Convert an instance of BuildingPreviousOperation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

