/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BuildingConstructionSettings;
import org.openapitools.client.model.BuildingLocation;
import org.openapitools.client.model.Inventory;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BuildingConstruction
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T00:07:12.329189600-03:00[America/Fortaleza]", comments = "Generator version: 7.19.0")
public class BuildingConstruction {
  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  @javax.annotation.Nullable
  private String reference;

  public static final String SERIALIZED_NAME_INVENTORY = "inventory";
  @SerializedName(SERIALIZED_NAME_INVENTORY)
  @javax.annotation.Nullable
  private Inventory inventory;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  @javax.annotation.Nullable
  private BigDecimal size;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  @javax.annotation.Nullable
  private BigDecimal time;

  public static final String SERIALIZED_NAME_TOTAL_TIME = "total_time";
  @SerializedName(SERIALIZED_NAME_TOTAL_TIME)
  @javax.annotation.Nullable
  private BigDecimal totalTime;

  public static final String SERIALIZED_NAME_PROGRESS = "progress";
  @SerializedName(SERIALIZED_NAME_PROGRESS)
  @javax.annotation.Nullable
  private BigDecimal progress;

  public static final String SERIALIZED_NAME_STAGE = "stage";
  @SerializedName(SERIALIZED_NAME_STAGE)
  @javax.annotation.Nullable
  private String stage;

  public static final String SERIALIZED_NAME_LAND = "land";
  @SerializedName(SERIALIZED_NAME_LAND)
  @javax.annotation.Nullable
  private List<BuildingLocation> land = new ArrayList<>();

  public static final String SERIALIZED_NAME_PROVIDER_ID = "provider_id";
  @SerializedName(SERIALIZED_NAME_PROVIDER_ID)
  @javax.annotation.Nullable
  private String providerId;

  public static final String SERIALIZED_NAME_SETTINGS = "settings";
  @SerializedName(SERIALIZED_NAME_SETTINGS)
  @javax.annotation.Nullable
  private BuildingConstructionSettings settings;

  public BuildingConstruction() {
  }

  public BuildingConstruction reference(@javax.annotation.Nullable String reference) {
    this.reference = reference;
    return this;
  }

  /**
   * Get reference
   * @return reference
   */
  @javax.annotation.Nullable
  public String getReference() {
    return reference;
  }

  public void setReference(@javax.annotation.Nullable String reference) {
    this.reference = reference;
  }


  public BuildingConstruction inventory(@javax.annotation.Nullable Inventory inventory) {
    this.inventory = inventory;
    return this;
  }

  /**
   * Get inventory
   * @return inventory
   */
  @javax.annotation.Nullable
  public Inventory getInventory() {
    return inventory;
  }

  public void setInventory(@javax.annotation.Nullable Inventory inventory) {
    this.inventory = inventory;
  }


  public BuildingConstruction size(@javax.annotation.Nullable BigDecimal size) {
    this.size = size;
    return this;
  }

  /**
   * Get size
   * @return size
   */
  @javax.annotation.Nullable
  public BigDecimal getSize() {
    return size;
  }

  public void setSize(@javax.annotation.Nullable BigDecimal size) {
    this.size = size;
  }


  public BuildingConstruction time(@javax.annotation.Nullable BigDecimal time) {
    this.time = time;
    return this;
  }

  /**
   * Get time
   * @return time
   */
  @javax.annotation.Nullable
  public BigDecimal getTime() {
    return time;
  }

  public void setTime(@javax.annotation.Nullable BigDecimal time) {
    this.time = time;
  }


  public BuildingConstruction totalTime(@javax.annotation.Nullable BigDecimal totalTime) {
    this.totalTime = totalTime;
    return this;
  }

  /**
   * Get totalTime
   * @return totalTime
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalTime() {
    return totalTime;
  }

  public void setTotalTime(@javax.annotation.Nullable BigDecimal totalTime) {
    this.totalTime = totalTime;
  }


  public BuildingConstruction progress(@javax.annotation.Nullable BigDecimal progress) {
    this.progress = progress;
    return this;
  }

  /**
   * Get progress
   * @return progress
   */
  @javax.annotation.Nullable
  public BigDecimal getProgress() {
    return progress;
  }

  public void setProgress(@javax.annotation.Nullable BigDecimal progress) {
    this.progress = progress;
  }


  public BuildingConstruction stage(@javax.annotation.Nullable String stage) {
    this.stage = stage;
    return this;
  }

  /**
   * Get stage
   * @return stage
   */
  @javax.annotation.Nullable
  public String getStage() {
    return stage;
  }

  public void setStage(@javax.annotation.Nullable String stage) {
    this.stage = stage;
  }


  public BuildingConstruction land(@javax.annotation.Nullable List<BuildingLocation> land) {
    this.land = land;
    return this;
  }

  public BuildingConstruction addLandItem(BuildingLocation landItem) {
    if (this.land == null) {
      this.land = new ArrayList<>();
    }
    this.land.add(landItem);
    return this;
  }

  /**
   * Get land
   * @return land
   */
  @javax.annotation.Nullable
  public List<BuildingLocation> getLand() {
    return land;
  }

  public void setLand(@javax.annotation.Nullable List<BuildingLocation> land) {
    this.land = land;
  }


  public BuildingConstruction providerId(@javax.annotation.Nullable String providerId) {
    this.providerId = providerId;
    return this;
  }

  /**
   * Get providerId
   * @return providerId
   */
  @javax.annotation.Nullable
  public String getProviderId() {
    return providerId;
  }

  public void setProviderId(@javax.annotation.Nullable String providerId) {
    this.providerId = providerId;
  }


  public BuildingConstruction settings(@javax.annotation.Nullable BuildingConstructionSettings settings) {
    this.settings = settings;
    return this;
  }

  /**
   * Get settings
   * @return settings
   */
  @javax.annotation.Nullable
  public BuildingConstructionSettings getSettings() {
    return settings;
  }

  public void setSettings(@javax.annotation.Nullable BuildingConstructionSettings settings) {
    this.settings = settings;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuildingConstruction buildingConstruction = (BuildingConstruction) o;
    return Objects.equals(this.reference, buildingConstruction.reference) &&
        Objects.equals(this.inventory, buildingConstruction.inventory) &&
        Objects.equals(this.size, buildingConstruction.size) &&
        Objects.equals(this.time, buildingConstruction.time) &&
        Objects.equals(this.totalTime, buildingConstruction.totalTime) &&
        Objects.equals(this.progress, buildingConstruction.progress) &&
        Objects.equals(this.stage, buildingConstruction.stage) &&
        Objects.equals(this.land, buildingConstruction.land) &&
        Objects.equals(this.providerId, buildingConstruction.providerId) &&
        Objects.equals(this.settings, buildingConstruction.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reference, inventory, size, time, totalTime, progress, stage, land, providerId, settings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuildingConstruction {\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    inventory: ").append(toIndentedString(inventory)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    totalTime: ").append(toIndentedString(totalTime)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("    land: ").append(toIndentedString(land)).append("\n");
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("reference", "inventory", "size", "time", "total_time", "progress", "stage", "land", "provider_id", "settings"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BuildingConstruction
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BuildingConstruction.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BuildingConstruction is not found in the empty JSON string", BuildingConstruction.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BuildingConstruction.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BuildingConstruction` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("reference") != null && !jsonObj.get("reference").isJsonNull()) && !jsonObj.get("reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reference").toString()));
      }
      // validate the optional field `inventory`
      if (jsonObj.get("inventory") != null && !jsonObj.get("inventory").isJsonNull()) {
        Inventory.validateJsonElement(jsonObj.get("inventory"));
      }
      if ((jsonObj.get("stage") != null && !jsonObj.get("stage").isJsonNull()) && !jsonObj.get("stage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `stage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stage").toString()));
      }
      if (jsonObj.get("land") != null && !jsonObj.get("land").isJsonNull()) {
        JsonArray jsonArrayland = jsonObj.getAsJsonArray("land");
        if (jsonArrayland != null) {
          // ensure the json data is an array
          if (!jsonObj.get("land").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `land` to be an array in the JSON string but got `%s`", jsonObj.get("land").toString()));
          }

          // validate the optional field `land` (array)
          for (int i = 0; i < jsonArrayland.size(); i++) {
            BuildingLocation.validateJsonElement(jsonArrayland.get(i));
          };
        }
      }
      if ((jsonObj.get("provider_id") != null && !jsonObj.get("provider_id").isJsonNull()) && !jsonObj.get("provider_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `provider_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider_id").toString()));
      }
      // validate the optional field `settings`
      if (jsonObj.get("settings") != null && !jsonObj.get("settings").isJsonNull()) {
        BuildingConstructionSettings.validateJsonElement(jsonObj.get("settings"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BuildingConstruction.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BuildingConstruction' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BuildingConstruction> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BuildingConstruction.class));

       return (TypeAdapter<T>) new TypeAdapter<BuildingConstruction>() {
           @Override
           public void write(JsonWriter out, BuildingConstruction value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BuildingConstruction read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BuildingConstruction given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BuildingConstruction
   * @throws IOException if the JSON string is invalid with respect to BuildingConstruction
   */
  public static BuildingConstruction fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BuildingConstruction.class);
  }

  /**
   * Convert an instance of BuildingConstruction to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

