/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BusinessAccount;
import org.openapitools.client.model.BusinessBuildings;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Business
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T16:48:14.721213200-03:00[America/Fortaleza]", comments = "Generator version: 7.19.0")
public class Business {
  public static final String SERIALIZED_NAME_ACCOUNT = "account";
  @SerializedName(SERIALIZED_NAME_ACCOUNT)
  @javax.annotation.Nullable
  private BusinessAccount account;

  public static final String SERIALIZED_NAME_BUILDINGS = "buildings";
  @SerializedName(SERIALIZED_NAME_BUILDINGS)
  @javax.annotation.Nullable
  private List<BusinessBuildings> buildings = new ArrayList<>();

  public static final String SERIALIZED_NAME_BUILDING_IDS = "building_ids";
  @SerializedName(SERIALIZED_NAME_BUILDING_IDS)
  @javax.annotation.Nullable
  private List<String> buildingIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  @javax.annotation.Nullable
  private String reference;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PORTRAIT = "portrait";
  @SerializedName(SERIALIZED_NAME_PORTRAIT)
  @javax.annotation.Nullable
  private String portrait;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @javax.annotation.Nullable
  private String accountId;

  public static final String SERIALIZED_NAME_OWNER_ID = "owner_id";
  @SerializedName(SERIALIZED_NAME_OWNER_ID)
  @javax.annotation.Nullable
  private String ownerId;

  public static final String SERIALIZED_NAME_TRANSPORT_IDS = "transport_ids";
  @SerializedName(SERIALIZED_NAME_TRANSPORT_IDS)
  @javax.annotation.Nullable
  private List<String> transportIds = new ArrayList<>();

  public Business() {
  }

  public Business account(@javax.annotation.Nullable BusinessAccount account) {
    this.account = account;
    return this;
  }

  /**
   * Get account
   * @return account
   */
  @javax.annotation.Nullable
  public BusinessAccount getAccount() {
    return account;
  }

  public void setAccount(@javax.annotation.Nullable BusinessAccount account) {
    this.account = account;
  }


  public Business buildings(@javax.annotation.Nullable List<BusinessBuildings> buildings) {
    this.buildings = buildings;
    return this;
  }

  public Business addBuildingsItem(BusinessBuildings buildingsItem) {
    if (this.buildings == null) {
      this.buildings = new ArrayList<>();
    }
    this.buildings.add(buildingsItem);
    return this;
  }

  /**
   * Get buildings
   * @return buildings
   */
  @javax.annotation.Nullable
  public List<BusinessBuildings> getBuildings() {
    return buildings;
  }

  public void setBuildings(@javax.annotation.Nullable List<BusinessBuildings> buildings) {
    this.buildings = buildings;
  }


  public Business buildingIds(@javax.annotation.Nullable List<String> buildingIds) {
    this.buildingIds = buildingIds;
    return this;
  }

  public Business addBuildingIdsItem(String buildingIdsItem) {
    if (this.buildingIds == null) {
      this.buildingIds = new ArrayList<>();
    }
    this.buildingIds.add(buildingIdsItem);
    return this;
  }

  /**
   * Get buildingIds
   * @return buildingIds
   */
  @javax.annotation.Nullable
  public List<String> getBuildingIds() {
    return buildingIds;
  }

  public void setBuildingIds(@javax.annotation.Nullable List<String> buildingIds) {
    this.buildingIds = buildingIds;
  }


  public Business id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Business reference(@javax.annotation.Nullable String reference) {
    this.reference = reference;
    return this;
  }

  /**
   * Get reference
   * @return reference
   */
  @javax.annotation.Nullable
  public String getReference() {
    return reference;
  }

  public void setReference(@javax.annotation.Nullable String reference) {
    this.reference = reference;
  }


  public Business name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Business portrait(@javax.annotation.Nullable String portrait) {
    this.portrait = portrait;
    return this;
  }

  /**
   * Get portrait
   * @return portrait
   */
  @javax.annotation.Nullable
  public String getPortrait() {
    return portrait;
  }

  public void setPortrait(@javax.annotation.Nullable String portrait) {
    this.portrait = portrait;
  }


  public Business accountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   * @return accountId
   */
  @javax.annotation.Nullable
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
  }


  public Business ownerId(@javax.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * Get ownerId
   * @return ownerId
   */
  @javax.annotation.Nullable
  public String getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(@javax.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
  }


  public Business transportIds(@javax.annotation.Nullable List<String> transportIds) {
    this.transportIds = transportIds;
    return this;
  }

  public Business addTransportIdsItem(String transportIdsItem) {
    if (this.transportIds == null) {
      this.transportIds = new ArrayList<>();
    }
    this.transportIds.add(transportIdsItem);
    return this;
  }

  /**
   * Get transportIds
   * @return transportIds
   */
  @javax.annotation.Nullable
  public List<String> getTransportIds() {
    return transportIds;
  }

  public void setTransportIds(@javax.annotation.Nullable List<String> transportIds) {
    this.transportIds = transportIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Business business = (Business) o;
    return Objects.equals(this.account, business.account) &&
        Objects.equals(this.buildings, business.buildings) &&
        Objects.equals(this.buildingIds, business.buildingIds) &&
        Objects.equals(this.id, business.id) &&
        Objects.equals(this.reference, business.reference) &&
        Objects.equals(this.name, business.name) &&
        Objects.equals(this.portrait, business.portrait) &&
        Objects.equals(this.accountId, business.accountId) &&
        Objects.equals(this.ownerId, business.ownerId) &&
        Objects.equals(this.transportIds, business.transportIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, buildings, buildingIds, id, reference, name, portrait, accountId, ownerId, transportIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Business {\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    buildings: ").append(toIndentedString(buildings)).append("\n");
    sb.append("    buildingIds: ").append(toIndentedString(buildingIds)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    portrait: ").append(toIndentedString(portrait)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    transportIds: ").append(toIndentedString(transportIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("account", "buildings", "building_ids", "id", "reference", "name", "portrait", "account_id", "owner_id", "transport_ids"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Business
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Business.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Business is not found in the empty JSON string", Business.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Business.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Business` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `account`
      if (jsonObj.get("account") != null && !jsonObj.get("account").isJsonNull()) {
        BusinessAccount.validateJsonElement(jsonObj.get("account"));
      }
      if (jsonObj.get("buildings") != null && !jsonObj.get("buildings").isJsonNull()) {
        JsonArray jsonArraybuildings = jsonObj.getAsJsonArray("buildings");
        if (jsonArraybuildings != null) {
          // ensure the json data is an array
          if (!jsonObj.get("buildings").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `buildings` to be an array in the JSON string but got `%s`", jsonObj.get("buildings").toString()));
          }

          // validate the optional field `buildings` (array)
          for (int i = 0; i < jsonArraybuildings.size(); i++) {
            BusinessBuildings.validateJsonElement(jsonArraybuildings.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("building_ids") != null && !jsonObj.get("building_ids").isJsonNull() && !jsonObj.get("building_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `building_ids` to be an array in the JSON string but got `%s`", jsonObj.get("building_ids").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("reference") != null && !jsonObj.get("reference").isJsonNull()) && !jsonObj.get("reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reference").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("portrait") != null && !jsonObj.get("portrait").isJsonNull()) && !jsonObj.get("portrait").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `portrait` to be a primitive type in the JSON string but got `%s`", jsonObj.get("portrait").toString()));
      }
      if ((jsonObj.get("account_id") != null && !jsonObj.get("account_id").isJsonNull()) && !jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
      if ((jsonObj.get("owner_id") != null && !jsonObj.get("owner_id").isJsonNull()) && !jsonObj.get("owner_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `owner_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner_id").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("transport_ids") != null && !jsonObj.get("transport_ids").isJsonNull() && !jsonObj.get("transport_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transport_ids` to be an array in the JSON string but got `%s`", jsonObj.get("transport_ids").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Business.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Business' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Business> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Business.class));

       return (TypeAdapter<T>) new TypeAdapter<Business>() {
           @Override
           public void write(JsonWriter out, Business value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Business read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Business given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Business
   * @throws IOException if the JSON string is invalid with respect to Business
   */
  public static Business fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Business.class);
  }

  /**
   * Convert an instance of Business to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

