/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ConstructionSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T16:48:14.721213200-03:00[America/Fortaleza]", comments = "Generator version: 7.19.0")
public class ConstructionSettings {
  public static final String SERIALIZED_NAME_HONOUR_LOW_STOCK = "honour_low_stock";
  @SerializedName(SERIALIZED_NAME_HONOUR_LOW_STOCK)
  @javax.annotation.Nullable
  private Boolean honourLowStock;

  public static final String SERIALIZED_NAME_PACE = "pace";
  @SerializedName(SERIALIZED_NAME_PACE)
  @javax.annotation.Nullable
  private BigDecimal pace;

  public ConstructionSettings() {
  }

  public ConstructionSettings honourLowStock(@javax.annotation.Nullable Boolean honourLowStock) {
    this.honourLowStock = honourLowStock;
    return this;
  }

  /**
   * Get honourLowStock
   * @return honourLowStock
   */
  @javax.annotation.Nullable
  public Boolean getHonourLowStock() {
    return honourLowStock;
  }

  public void setHonourLowStock(@javax.annotation.Nullable Boolean honourLowStock) {
    this.honourLowStock = honourLowStock;
  }


  public ConstructionSettings pace(@javax.annotation.Nullable BigDecimal pace) {
    this.pace = pace;
    return this;
  }

  /**
   * Get pace
   * @return pace
   */
  @javax.annotation.Nullable
  public BigDecimal getPace() {
    return pace;
  }

  public void setPace(@javax.annotation.Nullable BigDecimal pace) {
    this.pace = pace;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConstructionSettings constructionSettings = (ConstructionSettings) o;
    return Objects.equals(this.honourLowStock, constructionSettings.honourLowStock) &&
        Objects.equals(this.pace, constructionSettings.pace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(honourLowStock, pace);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConstructionSettings {\n");
    sb.append("    honourLowStock: ").append(toIndentedString(honourLowStock)).append("\n");
    sb.append("    pace: ").append(toIndentedString(pace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("honour_low_stock", "pace"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConstructionSettings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConstructionSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ConstructionSettings is not found in the empty JSON string", ConstructionSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConstructionSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ConstructionSettings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConstructionSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConstructionSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConstructionSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConstructionSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<ConstructionSettings>() {
           @Override
           public void write(JsonWriter out, ConstructionSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConstructionSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConstructionSettings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConstructionSettings
   * @throws IOException if the JSON string is invalid with respect to ConstructionSettings
   */
  public static ConstructionSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConstructionSettings.class);
  }

  /**
   * Convert an instance of ConstructionSettings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

