/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PrestigeImpact
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T01:19:29.594938500-03:00[America/Fortaleza]", comments = "Generator version: 7.19.0")
public class PrestigeImpact {
  public static final String SERIALIZED_NAME_FACTOR = "factor";
  @SerializedName(SERIALIZED_NAME_FACTOR)
  @javax.annotation.Nullable
  private String factor;

  public static final String SERIALIZED_NAME_IMPACT = "impact";
  @SerializedName(SERIALIZED_NAME_IMPACT)
  @javax.annotation.Nullable
  private String impact;

  public PrestigeImpact() {
  }

  public PrestigeImpact factor(@javax.annotation.Nullable String factor) {
    this.factor = factor;
    return this;
  }

  /**
   * Get factor
   * @return factor
   */
  @javax.annotation.Nullable
  public String getFactor() {
    return factor;
  }

  public void setFactor(@javax.annotation.Nullable String factor) {
    this.factor = factor;
  }


  public PrestigeImpact impact(@javax.annotation.Nullable String impact) {
    this.impact = impact;
    return this;
  }

  /**
   * Get impact
   * @return impact
   */
  @javax.annotation.Nullable
  public String getImpact() {
    return impact;
  }

  public void setImpact(@javax.annotation.Nullable String impact) {
    this.impact = impact;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrestigeImpact prestigeImpact = (PrestigeImpact) o;
    return Objects.equals(this.factor, prestigeImpact.factor) &&
        Objects.equals(this.impact, prestigeImpact.impact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(factor, impact);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrestigeImpact {\n");
    sb.append("    factor: ").append(toIndentedString(factor)).append("\n");
    sb.append("    impact: ").append(toIndentedString(impact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("factor", "impact"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PrestigeImpact
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PrestigeImpact.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PrestigeImpact is not found in the empty JSON string", PrestigeImpact.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PrestigeImpact.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PrestigeImpact` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("factor") != null && !jsonObj.get("factor").isJsonNull()) && !jsonObj.get("factor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `factor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("factor").toString()));
      }
      if ((jsonObj.get("impact") != null && !jsonObj.get("impact").isJsonNull()) && !jsonObj.get("impact").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `impact` to be a primitive type in the JSON string but got `%s`", jsonObj.get("impact").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PrestigeImpact.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PrestigeImpact' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PrestigeImpact> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PrestigeImpact.class));

       return (TypeAdapter<T>) new TypeAdapter<PrestigeImpact>() {
           @Override
           public void write(JsonWriter out, PrestigeImpact value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PrestigeImpact read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PrestigeImpact given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PrestigeImpact
   * @throws IOException if the JSON string is invalid with respect to PrestigeImpact
   */
  public static PrestigeImpact fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PrestigeImpact.class);
  }

  /**
   * Convert an instance of PrestigeImpact to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

