/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TownCommonersIncomeItems
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T16:48:14.721213200-03:00[America/Fortaleza]", comments = "Generator version: 7.19.0")
public class TownCommonersIncomeItems {
  public static final String SERIALIZED_NAME_PRODUCT = "product";
  @SerializedName(SERIALIZED_NAME_PRODUCT)
  @javax.annotation.Nullable
  private String product;

  public static final String SERIALIZED_NAME_BONUS = "bonus";
  @SerializedName(SERIALIZED_NAME_BONUS)
  @javax.annotation.Nullable
  private String bonus;

  public static final String SERIALIZED_NAME_DESIRE = "desire";
  @SerializedName(SERIALIZED_NAME_DESIRE)
  @javax.annotation.Nullable
  private String desire;

  public static final String SERIALIZED_NAME_REQUEST = "request";
  @SerializedName(SERIALIZED_NAME_REQUEST)
  @javax.annotation.Nullable
  private String request;

  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  @javax.annotation.Nullable
  private String result;

  public static final String SERIALIZED_NAME_BUDGET = "budget";
  @SerializedName(SERIALIZED_NAME_BUDGET)
  @javax.annotation.Nullable
  private String budget;

  public static final String SERIALIZED_NAME_WEIGHT = "weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  @javax.annotation.Nullable
  private String weight;

  public TownCommonersIncomeItems() {
  }

  public TownCommonersIncomeItems product(@javax.annotation.Nullable String product) {
    this.product = product;
    return this;
  }

  /**
   * Get product
   * @return product
   */
  @javax.annotation.Nullable
  public String getProduct() {
    return product;
  }

  public void setProduct(@javax.annotation.Nullable String product) {
    this.product = product;
  }


  public TownCommonersIncomeItems bonus(@javax.annotation.Nullable String bonus) {
    this.bonus = bonus;
    return this;
  }

  /**
   * Get bonus
   * @return bonus
   */
  @javax.annotation.Nullable
  public String getBonus() {
    return bonus;
  }

  public void setBonus(@javax.annotation.Nullable String bonus) {
    this.bonus = bonus;
  }


  public TownCommonersIncomeItems desire(@javax.annotation.Nullable String desire) {
    this.desire = desire;
    return this;
  }

  /**
   * Get desire
   * @return desire
   */
  @javax.annotation.Nullable
  public String getDesire() {
    return desire;
  }

  public void setDesire(@javax.annotation.Nullable String desire) {
    this.desire = desire;
  }


  public TownCommonersIncomeItems request(@javax.annotation.Nullable String request) {
    this.request = request;
    return this;
  }

  /**
   * Get request
   * @return request
   */
  @javax.annotation.Nullable
  public String getRequest() {
    return request;
  }

  public void setRequest(@javax.annotation.Nullable String request) {
    this.request = request;
  }


  public TownCommonersIncomeItems result(@javax.annotation.Nullable String result) {
    this.result = result;
    return this;
  }

  /**
   * Get result
   * @return result
   */
  @javax.annotation.Nullable
  public String getResult() {
    return result;
  }

  public void setResult(@javax.annotation.Nullable String result) {
    this.result = result;
  }


  public TownCommonersIncomeItems budget(@javax.annotation.Nullable String budget) {
    this.budget = budget;
    return this;
  }

  /**
   * Get budget
   * @return budget
   */
  @javax.annotation.Nullable
  public String getBudget() {
    return budget;
  }

  public void setBudget(@javax.annotation.Nullable String budget) {
    this.budget = budget;
  }


  public TownCommonersIncomeItems weight(@javax.annotation.Nullable String weight) {
    this.weight = weight;
    return this;
  }

  /**
   * Get weight
   * @return weight
   */
  @javax.annotation.Nullable
  public String getWeight() {
    return weight;
  }

  public void setWeight(@javax.annotation.Nullable String weight) {
    this.weight = weight;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TownCommonersIncomeItems townCommonersIncomeItems = (TownCommonersIncomeItems) o;
    return Objects.equals(this.product, townCommonersIncomeItems.product) &&
        Objects.equals(this.bonus, townCommonersIncomeItems.bonus) &&
        Objects.equals(this.desire, townCommonersIncomeItems.desire) &&
        Objects.equals(this.request, townCommonersIncomeItems.request) &&
        Objects.equals(this.result, townCommonersIncomeItems.result) &&
        Objects.equals(this.budget, townCommonersIncomeItems.budget) &&
        Objects.equals(this.weight, townCommonersIncomeItems.weight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(product, bonus, desire, request, result, budget, weight);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TownCommonersIncomeItems {\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    bonus: ").append(toIndentedString(bonus)).append("\n");
    sb.append("    desire: ").append(toIndentedString(desire)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    budget: ").append(toIndentedString(budget)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("product", "bonus", "desire", "request", "result", "budget", "weight"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TownCommonersIncomeItems
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TownCommonersIncomeItems.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TownCommonersIncomeItems is not found in the empty JSON string", TownCommonersIncomeItems.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TownCommonersIncomeItems.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TownCommonersIncomeItems` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("product") != null && !jsonObj.get("product").isJsonNull()) && !jsonObj.get("product").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `product` to be a primitive type in the JSON string but got `%s`", jsonObj.get("product").toString()));
      }
      if ((jsonObj.get("bonus") != null && !jsonObj.get("bonus").isJsonNull()) && !jsonObj.get("bonus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `bonus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bonus").toString()));
      }
      if ((jsonObj.get("desire") != null && !jsonObj.get("desire").isJsonNull()) && !jsonObj.get("desire").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `desire` to be a primitive type in the JSON string but got `%s`", jsonObj.get("desire").toString()));
      }
      if ((jsonObj.get("request") != null && !jsonObj.get("request").isJsonNull()) && !jsonObj.get("request").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `request` to be a primitive type in the JSON string but got `%s`", jsonObj.get("request").toString()));
      }
      if ((jsonObj.get("result") != null && !jsonObj.get("result").isJsonNull()) && !jsonObj.get("result").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `result` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result").toString()));
      }
      if ((jsonObj.get("budget") != null && !jsonObj.get("budget").isJsonNull()) && !jsonObj.get("budget").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `budget` to be a primitive type in the JSON string but got `%s`", jsonObj.get("budget").toString()));
      }
      if ((jsonObj.get("weight") != null && !jsonObj.get("weight").isJsonNull()) && !jsonObj.get("weight").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `weight` to be a primitive type in the JSON string but got `%s`", jsonObj.get("weight").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TownCommonersIncomeItems.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TownCommonersIncomeItems' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TownCommonersIncomeItems> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TownCommonersIncomeItems.class));

       return (TypeAdapter<T>) new TypeAdapter<TownCommonersIncomeItems>() {
           @Override
           public void write(JsonWriter out, TownCommonersIncomeItems value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TownCommonersIncomeItems read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TownCommonersIncomeItems given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TownCommonersIncomeItems
   * @throws IOException if the JSON string is invalid with respect to TownCommonersIncomeItems
   */
  public static TownCommonersIncomeItems fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TownCommonersIncomeItems.class);
  }

  /**
   * Convert an instance of TownCommonersIncomeItems to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

