/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Location;
import org.openapitools.client.model.TownChurch;
import org.openapitools.client.model.TownCommoners;
import org.openapitools.client.model.TownCulture;
import org.openapitools.client.model.TownDomain;
import org.openapitools.client.model.TownGovernment;
import org.openapitools.client.model.TownNavigationZones;
import org.openapitools.client.model.TownState;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Town
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T16:48:14.721213200-03:00[America/Fortaleza]", comments = "Generator version: 7.19.0")
public class Town {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  @javax.annotation.Nullable
  private Location location;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  @javax.annotation.Nullable
  private BigDecimal region;

  public static final String SERIALIZED_NAME_CAPITAL_ID = "capital_id";
  @SerializedName(SERIALIZED_NAME_CAPITAL_ID)
  @javax.annotation.Nullable
  private String capitalId;

  public static final String SERIALIZED_NAME_CENTER_IDS = "center_ids";
  @SerializedName(SERIALIZED_NAME_CENTER_IDS)
  @javax.annotation.Nullable
  private List<BigDecimal> centerIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_DOMAIN = "domain";
  @SerializedName(SERIALIZED_NAME_DOMAIN)
  @javax.annotation.Nullable
  private TownDomain domain;

  public static final String SERIALIZED_NAME_HOUSEHOLD_IDS = "household_ids";
  @SerializedName(SERIALIZED_NAME_HOUSEHOLD_IDS)
  @javax.annotation.Nullable
  private List<String> householdIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_COMMONERS = "commoners";
  @SerializedName(SERIALIZED_NAME_COMMONERS)
  @javax.annotation.Nullable
  private TownCommoners commoners;

  public static final String SERIALIZED_NAME_GOVERNMENT = "government";
  @SerializedName(SERIALIZED_NAME_GOVERNMENT)
  @javax.annotation.Nullable
  private TownGovernment government;

  public static final String SERIALIZED_NAME_CHURCH = "church";
  @SerializedName(SERIALIZED_NAME_CHURCH)
  @javax.annotation.Nullable
  private TownChurch church;

  public static final String SERIALIZED_NAME_NAVIGATION_ZONES = "navigation_zones";
  @SerializedName(SERIALIZED_NAME_NAVIGATION_ZONES)
  @javax.annotation.Nullable
  private TownNavigationZones navigationZones;

  public static final String SERIALIZED_NAME_CULTURE = "culture";
  @SerializedName(SERIALIZED_NAME_CULTURE)
  @javax.annotation.Nullable
  private TownCulture culture;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nullable
  private TownState state;

  public static final String SERIALIZED_NAME_TS = "_ts";
  @SerializedName(SERIALIZED_NAME_TS)
  @javax.annotation.Nullable
  private BigDecimal ts;

  public Town() {
  }

  public Town id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Town name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Town location(@javax.annotation.Nullable Location location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @javax.annotation.Nullable
  public Location getLocation() {
    return location;
  }

  public void setLocation(@javax.annotation.Nullable Location location) {
    this.location = location;
  }


  public Town region(@javax.annotation.Nullable BigDecimal region) {
    this.region = region;
    return this;
  }

  /**
   * Get region
   * @return region
   */
  @javax.annotation.Nullable
  public BigDecimal getRegion() {
    return region;
  }

  public void setRegion(@javax.annotation.Nullable BigDecimal region) {
    this.region = region;
  }


  public Town capitalId(@javax.annotation.Nullable String capitalId) {
    this.capitalId = capitalId;
    return this;
  }

  /**
   * Get capitalId
   * @return capitalId
   */
  @javax.annotation.Nullable
  public String getCapitalId() {
    return capitalId;
  }

  public void setCapitalId(@javax.annotation.Nullable String capitalId) {
    this.capitalId = capitalId;
  }


  public Town centerIds(@javax.annotation.Nullable List<BigDecimal> centerIds) {
    this.centerIds = centerIds;
    return this;
  }

  public Town addCenterIdsItem(BigDecimal centerIdsItem) {
    if (this.centerIds == null) {
      this.centerIds = new ArrayList<>();
    }
    this.centerIds.add(centerIdsItem);
    return this;
  }

  /**
   * Get centerIds
   * @return centerIds
   */
  @javax.annotation.Nullable
  public List<BigDecimal> getCenterIds() {
    return centerIds;
  }

  public void setCenterIds(@javax.annotation.Nullable List<BigDecimal> centerIds) {
    this.centerIds = centerIds;
  }


  public Town domain(@javax.annotation.Nullable TownDomain domain) {
    this.domain = domain;
    return this;
  }

  /**
   * Get domain
   * @return domain
   */
  @javax.annotation.Nullable
  public TownDomain getDomain() {
    return domain;
  }

  public void setDomain(@javax.annotation.Nullable TownDomain domain) {
    this.domain = domain;
  }


  public Town householdIds(@javax.annotation.Nullable List<String> householdIds) {
    this.householdIds = householdIds;
    return this;
  }

  public Town addHouseholdIdsItem(String householdIdsItem) {
    if (this.householdIds == null) {
      this.householdIds = new ArrayList<>();
    }
    this.householdIds.add(householdIdsItem);
    return this;
  }

  /**
   * Get householdIds
   * @return householdIds
   */
  @javax.annotation.Nullable
  public List<String> getHouseholdIds() {
    return householdIds;
  }

  public void setHouseholdIds(@javax.annotation.Nullable List<String> householdIds) {
    this.householdIds = householdIds;
  }


  public Town commoners(@javax.annotation.Nullable TownCommoners commoners) {
    this.commoners = commoners;
    return this;
  }

  /**
   * Get commoners
   * @return commoners
   */
  @javax.annotation.Nullable
  public TownCommoners getCommoners() {
    return commoners;
  }

  public void setCommoners(@javax.annotation.Nullable TownCommoners commoners) {
    this.commoners = commoners;
  }


  public Town government(@javax.annotation.Nullable TownGovernment government) {
    this.government = government;
    return this;
  }

  /**
   * Get government
   * @return government
   */
  @javax.annotation.Nullable
  public TownGovernment getGovernment() {
    return government;
  }

  public void setGovernment(@javax.annotation.Nullable TownGovernment government) {
    this.government = government;
  }


  public Town church(@javax.annotation.Nullable TownChurch church) {
    this.church = church;
    return this;
  }

  /**
   * Get church
   * @return church
   */
  @javax.annotation.Nullable
  public TownChurch getChurch() {
    return church;
  }

  public void setChurch(@javax.annotation.Nullable TownChurch church) {
    this.church = church;
  }


  public Town navigationZones(@javax.annotation.Nullable TownNavigationZones navigationZones) {
    this.navigationZones = navigationZones;
    return this;
  }

  /**
   * Get navigationZones
   * @return navigationZones
   */
  @javax.annotation.Nullable
  public TownNavigationZones getNavigationZones() {
    return navigationZones;
  }

  public void setNavigationZones(@javax.annotation.Nullable TownNavigationZones navigationZones) {
    this.navigationZones = navigationZones;
  }


  public Town culture(@javax.annotation.Nullable TownCulture culture) {
    this.culture = culture;
    return this;
  }

  /**
   * Get culture
   * @return culture
   */
  @javax.annotation.Nullable
  public TownCulture getCulture() {
    return culture;
  }

  public void setCulture(@javax.annotation.Nullable TownCulture culture) {
    this.culture = culture;
  }


  public Town state(@javax.annotation.Nullable TownState state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nullable
  public TownState getState() {
    return state;
  }

  public void setState(@javax.annotation.Nullable TownState state) {
    this.state = state;
  }


  public Town ts(@javax.annotation.Nullable BigDecimal ts) {
    this.ts = ts;
    return this;
  }

  /**
   * Get ts
   * @return ts
   */
  @javax.annotation.Nullable
  public BigDecimal getTs() {
    return ts;
  }

  public void setTs(@javax.annotation.Nullable BigDecimal ts) {
    this.ts = ts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Town town = (Town) o;
    return Objects.equals(this.id, town.id) &&
        Objects.equals(this.name, town.name) &&
        Objects.equals(this.location, town.location) &&
        Objects.equals(this.region, town.region) &&
        Objects.equals(this.capitalId, town.capitalId) &&
        Objects.equals(this.centerIds, town.centerIds) &&
        Objects.equals(this.domain, town.domain) &&
        Objects.equals(this.householdIds, town.householdIds) &&
        Objects.equals(this.commoners, town.commoners) &&
        Objects.equals(this.government, town.government) &&
        Objects.equals(this.church, town.church) &&
        Objects.equals(this.navigationZones, town.navigationZones) &&
        Objects.equals(this.culture, town.culture) &&
        Objects.equals(this.state, town.state) &&
        Objects.equals(this.ts, town.ts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, location, region, capitalId, centerIds, domain, householdIds, commoners, government, church, navigationZones, culture, state, ts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Town {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    capitalId: ").append(toIndentedString(capitalId)).append("\n");
    sb.append("    centerIds: ").append(toIndentedString(centerIds)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    householdIds: ").append(toIndentedString(householdIds)).append("\n");
    sb.append("    commoners: ").append(toIndentedString(commoners)).append("\n");
    sb.append("    government: ").append(toIndentedString(government)).append("\n");
    sb.append("    church: ").append(toIndentedString(church)).append("\n");
    sb.append("    navigationZones: ").append(toIndentedString(navigationZones)).append("\n");
    sb.append("    culture: ").append(toIndentedString(culture)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "location", "region", "capital_id", "center_ids", "domain", "household_ids", "commoners", "government", "church", "navigation_zones", "culture", "state", "_ts"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Town
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Town.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Town is not found in the empty JSON string", Town.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Town.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Town` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `location`
      if (jsonObj.get("location") != null && !jsonObj.get("location").isJsonNull()) {
        Location.validateJsonElement(jsonObj.get("location"));
      }
      if ((jsonObj.get("capital_id") != null && !jsonObj.get("capital_id").isJsonNull()) && !jsonObj.get("capital_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `capital_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("capital_id").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("center_ids") != null && !jsonObj.get("center_ids").isJsonNull() && !jsonObj.get("center_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `center_ids` to be an array in the JSON string but got `%s`", jsonObj.get("center_ids").toString()));
      }
      // validate the optional field `domain`
      if (jsonObj.get("domain") != null && !jsonObj.get("domain").isJsonNull()) {
        TownDomain.validateJsonElement(jsonObj.get("domain"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("household_ids") != null && !jsonObj.get("household_ids").isJsonNull() && !jsonObj.get("household_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `household_ids` to be an array in the JSON string but got `%s`", jsonObj.get("household_ids").toString()));
      }
      // validate the optional field `commoners`
      if (jsonObj.get("commoners") != null && !jsonObj.get("commoners").isJsonNull()) {
        TownCommoners.validateJsonElement(jsonObj.get("commoners"));
      }
      // validate the optional field `government`
      if (jsonObj.get("government") != null && !jsonObj.get("government").isJsonNull()) {
        TownGovernment.validateJsonElement(jsonObj.get("government"));
      }
      // validate the optional field `church`
      if (jsonObj.get("church") != null && !jsonObj.get("church").isJsonNull()) {
        TownChurch.validateJsonElement(jsonObj.get("church"));
      }
      // validate the optional field `navigation_zones`
      if (jsonObj.get("navigation_zones") != null && !jsonObj.get("navigation_zones").isJsonNull()) {
        TownNavigationZones.validateJsonElement(jsonObj.get("navigation_zones"));
      }
      // validate the optional field `culture`
      if (jsonObj.get("culture") != null && !jsonObj.get("culture").isJsonNull()) {
        TownCulture.validateJsonElement(jsonObj.get("culture"));
      }
      // validate the optional field `state`
      if (jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) {
        TownState.validateJsonElement(jsonObj.get("state"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Town.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Town' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Town> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Town.class));

       return (TypeAdapter<T>) new TypeAdapter<Town>() {
           @Override
           public void write(JsonWriter out, Town value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Town read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Town given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Town
   * @throws IOException if the JSON string is invalid with respect to Town
   */
  public static Town fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Town.class);
  }

  /**
   * Convert an instance of Town to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

