/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TownGovernmentTaxesCollected
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T16:48:14.721213200-03:00[America/Fortaleza]", comments = "Generator version: 7.19.0")
public class TownGovernmentTaxesCollected {
  public static final String SERIALIZED_NAME_PAYMENTS = "payments";
  @SerializedName(SERIALIZED_NAME_PAYMENTS)
  @javax.annotation.Nullable
  private String payments;

  public static final String SERIALIZED_NAME_LAND_TAX = "land_tax";
  @SerializedName(SERIALIZED_NAME_LAND_TAX)
  @javax.annotation.Nullable
  private String landTax;

  public static final String SERIALIZED_NAME_STRUCTURE_TAX = "structure_tax";
  @SerializedName(SERIALIZED_NAME_STRUCTURE_TAX)
  @javax.annotation.Nullable
  private String structureTax;

  public static final String SERIALIZED_NAME_DELIVERY_FEES = "delivery_fees";
  @SerializedName(SERIALIZED_NAME_DELIVERY_FEES)
  @javax.annotation.Nullable
  private String deliveryFees;

  public static final String SERIALIZED_NAME_TRANSPORT_FEES = "transport_fees";
  @SerializedName(SERIALIZED_NAME_TRANSPORT_FEES)
  @javax.annotation.Nullable
  private String transportFees;

  public TownGovernmentTaxesCollected() {
  }

  public TownGovernmentTaxesCollected payments(@javax.annotation.Nullable String payments) {
    this.payments = payments;
    return this;
  }

  /**
   * Get payments
   * @return payments
   */
  @javax.annotation.Nullable
  public String getPayments() {
    return payments;
  }

  public void setPayments(@javax.annotation.Nullable String payments) {
    this.payments = payments;
  }


  public TownGovernmentTaxesCollected landTax(@javax.annotation.Nullable String landTax) {
    this.landTax = landTax;
    return this;
  }

  /**
   * Get landTax
   * @return landTax
   */
  @javax.annotation.Nullable
  public String getLandTax() {
    return landTax;
  }

  public void setLandTax(@javax.annotation.Nullable String landTax) {
    this.landTax = landTax;
  }


  public TownGovernmentTaxesCollected structureTax(@javax.annotation.Nullable String structureTax) {
    this.structureTax = structureTax;
    return this;
  }

  /**
   * Get structureTax
   * @return structureTax
   */
  @javax.annotation.Nullable
  public String getStructureTax() {
    return structureTax;
  }

  public void setStructureTax(@javax.annotation.Nullable String structureTax) {
    this.structureTax = structureTax;
  }


  public TownGovernmentTaxesCollected deliveryFees(@javax.annotation.Nullable String deliveryFees) {
    this.deliveryFees = deliveryFees;
    return this;
  }

  /**
   * Get deliveryFees
   * @return deliveryFees
   */
  @javax.annotation.Nullable
  public String getDeliveryFees() {
    return deliveryFees;
  }

  public void setDeliveryFees(@javax.annotation.Nullable String deliveryFees) {
    this.deliveryFees = deliveryFees;
  }


  public TownGovernmentTaxesCollected transportFees(@javax.annotation.Nullable String transportFees) {
    this.transportFees = transportFees;
    return this;
  }

  /**
   * Get transportFees
   * @return transportFees
   */
  @javax.annotation.Nullable
  public String getTransportFees() {
    return transportFees;
  }

  public void setTransportFees(@javax.annotation.Nullable String transportFees) {
    this.transportFees = transportFees;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TownGovernmentTaxesCollected townGovernmentTaxesCollected = (TownGovernmentTaxesCollected) o;
    return Objects.equals(this.payments, townGovernmentTaxesCollected.payments) &&
        Objects.equals(this.landTax, townGovernmentTaxesCollected.landTax) &&
        Objects.equals(this.structureTax, townGovernmentTaxesCollected.structureTax) &&
        Objects.equals(this.deliveryFees, townGovernmentTaxesCollected.deliveryFees) &&
        Objects.equals(this.transportFees, townGovernmentTaxesCollected.transportFees);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payments, landTax, structureTax, deliveryFees, transportFees);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TownGovernmentTaxesCollected {\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    landTax: ").append(toIndentedString(landTax)).append("\n");
    sb.append("    structureTax: ").append(toIndentedString(structureTax)).append("\n");
    sb.append("    deliveryFees: ").append(toIndentedString(deliveryFees)).append("\n");
    sb.append("    transportFees: ").append(toIndentedString(transportFees)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("payments", "land_tax", "structure_tax", "delivery_fees", "transport_fees"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TownGovernmentTaxesCollected
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TownGovernmentTaxesCollected.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TownGovernmentTaxesCollected is not found in the empty JSON string", TownGovernmentTaxesCollected.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TownGovernmentTaxesCollected.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TownGovernmentTaxesCollected` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("payments") != null && !jsonObj.get("payments").isJsonNull()) && !jsonObj.get("payments").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payments` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payments").toString()));
      }
      if ((jsonObj.get("land_tax") != null && !jsonObj.get("land_tax").isJsonNull()) && !jsonObj.get("land_tax").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `land_tax` to be a primitive type in the JSON string but got `%s`", jsonObj.get("land_tax").toString()));
      }
      if ((jsonObj.get("structure_tax") != null && !jsonObj.get("structure_tax").isJsonNull()) && !jsonObj.get("structure_tax").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `structure_tax` to be a primitive type in the JSON string but got `%s`", jsonObj.get("structure_tax").toString()));
      }
      if ((jsonObj.get("delivery_fees") != null && !jsonObj.get("delivery_fees").isJsonNull()) && !jsonObj.get("delivery_fees").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `delivery_fees` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delivery_fees").toString()));
      }
      if ((jsonObj.get("transport_fees") != null && !jsonObj.get("transport_fees").isJsonNull()) && !jsonObj.get("transport_fees").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transport_fees` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transport_fees").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TownGovernmentTaxesCollected.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TownGovernmentTaxesCollected' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TownGovernmentTaxesCollected> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TownGovernmentTaxesCollected.class));

       return (TypeAdapter<T>) new TypeAdapter<TownGovernmentTaxesCollected>() {
           @Override
           public void write(JsonWriter out, TownGovernmentTaxesCollected value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TownGovernmentTaxesCollected read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TownGovernmentTaxesCollected given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TownGovernmentTaxesCollected
   * @throws IOException if the JSON string is invalid with respect to TownGovernmentTaxesCollected
   */
  public static TownGovernmentTaxesCollected fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TownGovernmentTaxesCollected.class);
  }

  /**
   * Convert an instance of TownGovernmentTaxesCollected to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

