/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.TownCommonersIncomeItems;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TownGovernmentSpending
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T16:48:14.721213200-03:00[America/Fortaleza]", comments = "Generator version: 7.19.0")
public class TownGovernmentSpending {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_MIGRATION = "migration";
  @SerializedName(SERIALIZED_NAME_MIGRATION)
  @javax.annotation.Nullable
  private String migration;

  public static final String SERIALIZED_NAME_BUDGET = "budget";
  @SerializedName(SERIALIZED_NAME_BUDGET)
  @javax.annotation.Nullable
  private String budget;

  public static final String SERIALIZED_NAME_SATISFACTION = "satisfaction";
  @SerializedName(SERIALIZED_NAME_SATISFACTION)
  @javax.annotation.Nullable
  private String satisfaction;

  public static final String SERIALIZED_NAME_PRODUCTS = "products";
  @SerializedName(SERIALIZED_NAME_PRODUCTS)
  @javax.annotation.Nullable
  private List<TownCommonersIncomeItems> products = new ArrayList<>();

  public TownGovernmentSpending() {
  }

  public TownGovernmentSpending name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public TownGovernmentSpending migration(@javax.annotation.Nullable String migration) {
    this.migration = migration;
    return this;
  }

  /**
   * Get migration
   * @return migration
   */
  @javax.annotation.Nullable
  public String getMigration() {
    return migration;
  }

  public void setMigration(@javax.annotation.Nullable String migration) {
    this.migration = migration;
  }


  public TownGovernmentSpending budget(@javax.annotation.Nullable String budget) {
    this.budget = budget;
    return this;
  }

  /**
   * Get budget
   * @return budget
   */
  @javax.annotation.Nullable
  public String getBudget() {
    return budget;
  }

  public void setBudget(@javax.annotation.Nullable String budget) {
    this.budget = budget;
  }


  public TownGovernmentSpending satisfaction(@javax.annotation.Nullable String satisfaction) {
    this.satisfaction = satisfaction;
    return this;
  }

  /**
   * Get satisfaction
   * @return satisfaction
   */
  @javax.annotation.Nullable
  public String getSatisfaction() {
    return satisfaction;
  }

  public void setSatisfaction(@javax.annotation.Nullable String satisfaction) {
    this.satisfaction = satisfaction;
  }


  public TownGovernmentSpending products(@javax.annotation.Nullable List<TownCommonersIncomeItems> products) {
    this.products = products;
    return this;
  }

  public TownGovernmentSpending addProductsItem(TownCommonersIncomeItems productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

  /**
   * Get products
   * @return products
   */
  @javax.annotation.Nullable
  public List<TownCommonersIncomeItems> getProducts() {
    return products;
  }

  public void setProducts(@javax.annotation.Nullable List<TownCommonersIncomeItems> products) {
    this.products = products;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TownGovernmentSpending townGovernmentSpending = (TownGovernmentSpending) o;
    return Objects.equals(this.name, townGovernmentSpending.name) &&
        Objects.equals(this.migration, townGovernmentSpending.migration) &&
        Objects.equals(this.budget, townGovernmentSpending.budget) &&
        Objects.equals(this.satisfaction, townGovernmentSpending.satisfaction) &&
        Objects.equals(this.products, townGovernmentSpending.products);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, migration, budget, satisfaction, products);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TownGovernmentSpending {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    migration: ").append(toIndentedString(migration)).append("\n");
    sb.append("    budget: ").append(toIndentedString(budget)).append("\n");
    sb.append("    satisfaction: ").append(toIndentedString(satisfaction)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "migration", "budget", "satisfaction", "products"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TownGovernmentSpending
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TownGovernmentSpending.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TownGovernmentSpending is not found in the empty JSON string", TownGovernmentSpending.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TownGovernmentSpending.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TownGovernmentSpending` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("migration") != null && !jsonObj.get("migration").isJsonNull()) && !jsonObj.get("migration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `migration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("migration").toString()));
      }
      if ((jsonObj.get("budget") != null && !jsonObj.get("budget").isJsonNull()) && !jsonObj.get("budget").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `budget` to be a primitive type in the JSON string but got `%s`", jsonObj.get("budget").toString()));
      }
      if ((jsonObj.get("satisfaction") != null && !jsonObj.get("satisfaction").isJsonNull()) && !jsonObj.get("satisfaction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `satisfaction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("satisfaction").toString()));
      }
      if (jsonObj.get("products") != null && !jsonObj.get("products").isJsonNull()) {
        JsonArray jsonArrayproducts = jsonObj.getAsJsonArray("products");
        if (jsonArrayproducts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("products").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `products` to be an array in the JSON string but got `%s`", jsonObj.get("products").toString()));
          }

          // validate the optional field `products` (array)
          for (int i = 0; i < jsonArrayproducts.size(); i++) {
            TownCommonersIncomeItems.validateJsonElement(jsonArrayproducts.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TownGovernmentSpending.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TownGovernmentSpending' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TownGovernmentSpending> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TownGovernmentSpending.class));

       return (TypeAdapter<T>) new TypeAdapter<TownGovernmentSpending>() {
           @Override
           public void write(JsonWriter out, TownGovernmentSpending value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TownGovernmentSpending read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TownGovernmentSpending given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TownGovernmentSpending
   * @throws IOException if the JSON string is invalid with respect to TownGovernmentSpending
   */
  public static TownGovernmentSpending fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TownGovernmentSpending.class);
  }

  /**
   * Convert an instance of TownGovernmentSpending to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

