/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.TownGovernmentSpending;
import org.openapitools.client.model.TownGovernmentTaxesCollected;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TownGovernment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T16:48:14.721213200-03:00[America/Fortaleza]", comments = "Generator version: 7.19.0")
public class TownGovernment {
  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @javax.annotation.Nullable
  private String accountId;

  public static final String SERIALIZED_NAME_SPENDING = "spending";
  @SerializedName(SERIALIZED_NAME_SPENDING)
  @javax.annotation.Nullable
  private List<TownGovernmentSpending> spending = new ArrayList<>();

  public static final String SERIALIZED_NAME_TAXES_COLLECTED = "taxes_collected";
  @SerializedName(SERIALIZED_NAME_TAXES_COLLECTED)
  @javax.annotation.Nullable
  private TownGovernmentTaxesCollected taxesCollected;

  public TownGovernment() {
  }

  public TownGovernment accountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   * @return accountId
   */
  @javax.annotation.Nullable
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
  }


  public TownGovernment spending(@javax.annotation.Nullable List<TownGovernmentSpending> spending) {
    this.spending = spending;
    return this;
  }

  public TownGovernment addSpendingItem(TownGovernmentSpending spendingItem) {
    if (this.spending == null) {
      this.spending = new ArrayList<>();
    }
    this.spending.add(spendingItem);
    return this;
  }

  /**
   * Get spending
   * @return spending
   */
  @javax.annotation.Nullable
  public List<TownGovernmentSpending> getSpending() {
    return spending;
  }

  public void setSpending(@javax.annotation.Nullable List<TownGovernmentSpending> spending) {
    this.spending = spending;
  }


  public TownGovernment taxesCollected(@javax.annotation.Nullable TownGovernmentTaxesCollected taxesCollected) {
    this.taxesCollected = taxesCollected;
    return this;
  }

  /**
   * Get taxesCollected
   * @return taxesCollected
   */
  @javax.annotation.Nullable
  public TownGovernmentTaxesCollected getTaxesCollected() {
    return taxesCollected;
  }

  public void setTaxesCollected(@javax.annotation.Nullable TownGovernmentTaxesCollected taxesCollected) {
    this.taxesCollected = taxesCollected;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TownGovernment townGovernment = (TownGovernment) o;
    return Objects.equals(this.accountId, townGovernment.accountId) &&
        Objects.equals(this.spending, townGovernment.spending) &&
        Objects.equals(this.taxesCollected, townGovernment.taxesCollected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, spending, taxesCollected);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TownGovernment {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    spending: ").append(toIndentedString(spending)).append("\n");
    sb.append("    taxesCollected: ").append(toIndentedString(taxesCollected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("account_id", "spending", "taxes_collected"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TownGovernment
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TownGovernment.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TownGovernment is not found in the empty JSON string", TownGovernment.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TownGovernment.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TownGovernment` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("account_id") != null && !jsonObj.get("account_id").isJsonNull()) && !jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
      if (jsonObj.get("spending") != null && !jsonObj.get("spending").isJsonNull()) {
        JsonArray jsonArrayspending = jsonObj.getAsJsonArray("spending");
        if (jsonArrayspending != null) {
          // ensure the json data is an array
          if (!jsonObj.get("spending").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `spending` to be an array in the JSON string but got `%s`", jsonObj.get("spending").toString()));
          }

          // validate the optional field `spending` (array)
          for (int i = 0; i < jsonArrayspending.size(); i++) {
            TownGovernmentSpending.validateJsonElement(jsonArrayspending.get(i));
          };
        }
      }
      // validate the optional field `taxes_collected`
      if (jsonObj.get("taxes_collected") != null && !jsonObj.get("taxes_collected").isJsonNull()) {
        TownGovernmentTaxesCollected.validateJsonElement(jsonObj.get("taxes_collected"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TownGovernment.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TownGovernment' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TownGovernment> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TownGovernment.class));

       return (TypeAdapter<T>) new TypeAdapter<TownGovernment>() {
           @Override
           public void write(JsonWriter out, TownGovernment value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TownGovernment read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TownGovernment given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TownGovernment
   * @throws IOException if the JSON string is invalid with respect to TownGovernment
   */
  public static TownGovernment fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TownGovernment.class);
  }

  /**
   * Convert an instance of TownGovernment to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

