/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Building from './model/Building';
import BuildingConstruction from './model/BuildingConstruction';
import BuildingDeliveryCost from './model/BuildingDeliveryCost';
import BuildingPreviousOperation from './model/BuildingPreviousOperation';
import BuildingProducer from './model/BuildingProducer';
import Business from './model/Business';
import BusinessAccount from './model/BusinessAccount';
import BusinessBuildings from './model/BusinessBuildings';
import CommonersTownState from './model/CommonersTownState';
import ConstructionSettings from './model/ConstructionSettings';
import DomainPlot from './model/DomainPlot';
import DomainPlotStructure from './model/DomainPlotStructure';
import Error from './model/Error';
import Holdings from './model/Holdings';
import Household from './model/Household';
import HouseholdCaps from './model/HouseholdCaps';
import HouseholdSustenance from './model/HouseholdSustenance';
import Inventory from './model/Inventory';
import InventoryAccount from './model/InventoryAccount';
import InventoryAssets from './model/InventoryAssets';
import InventoryFlows from './model/InventoryFlows';
import InventoryPastFlows from './model/InventoryPastFlows';
import Location from './model/Location';
import MapRegion from './model/MapRegion';
import Player from './model/Player';
import PlayerActivity from './model/PlayerActivity';
import PlayerSettings from './model/PlayerSettings';
import PlayerSettingsEmail from './model/PlayerSettingsEmail';
import PlayerSettingsNotifications from './model/PlayerSettingsNotifications';
import PrestigeImpact from './model/PrestigeImpact';
import ProductAsset from './model/ProductAsset';
import ProductFlow from './model/ProductFlow';
import ProductHolding from './model/ProductHolding';
import ProductManager from './model/ProductManager';
import ProductPastFlow from './model/ProductPastFlow';
import Specialization from './model/Specialization';
import SpecializationPoints from './model/SpecializationPoints';
import Town from './model/Town';
import TownChurch from './model/TownChurch';
import TownCommoners from './model/TownCommoners';
import TownCommonersIncome from './model/TownCommonersIncome';
import TownCommonersIncomeItems from './model/TownCommonersIncomeItems';
import TownCommonersSpending from './model/TownCommonersSpending';
import TownCulture from './model/TownCulture';
import TownDomain from './model/TownDomain';
import TownGovernment from './model/TownGovernment';
import TownGovernmentSpending from './model/TownGovernmentSpending';
import TownGovernmentTaxesCollected from './model/TownGovernmentTaxesCollected';
import TownNavigationZones from './model/TownNavigationZones';
import TownSimple from './model/TownSimple';
import TownState from './model/TownState';
import Worker from './model/Worker';
import WorkerSkills from './model/WorkerSkills';
import DefaultApi from './api/DefaultApi';


/**
* Mercatorio.js is a library that provides a easier way to interact with the Mercatorio API, allowing developers to make more third party applications and tools for the Mercatorio ecosystem..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var mercatoriojs = require('index'); // See note below*.
* var xxxSvc = new mercatoriojs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new mercatoriojs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new mercatoriojs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new mercatoriojs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Building model constructor.
     * @property {module:model/Building}
     */
    Building,

    /**
     * The BuildingConstruction model constructor.
     * @property {module:model/BuildingConstruction}
     */
    BuildingConstruction,

    /**
     * The BuildingDeliveryCost model constructor.
     * @property {module:model/BuildingDeliveryCost}
     */
    BuildingDeliveryCost,

    /**
     * The BuildingPreviousOperation model constructor.
     * @property {module:model/BuildingPreviousOperation}
     */
    BuildingPreviousOperation,

    /**
     * The BuildingProducer model constructor.
     * @property {module:model/BuildingProducer}
     */
    BuildingProducer,

    /**
     * The Business model constructor.
     * @property {module:model/Business}
     */
    Business,

    /**
     * The BusinessAccount model constructor.
     * @property {module:model/BusinessAccount}
     */
    BusinessAccount,

    /**
     * The BusinessBuildings model constructor.
     * @property {module:model/BusinessBuildings}
     */
    BusinessBuildings,

    /**
     * The CommonersTownState model constructor.
     * @property {module:model/CommonersTownState}
     */
    CommonersTownState,

    /**
     * The ConstructionSettings model constructor.
     * @property {module:model/ConstructionSettings}
     */
    ConstructionSettings,

    /**
     * The DomainPlot model constructor.
     * @property {module:model/DomainPlot}
     */
    DomainPlot,

    /**
     * The DomainPlotStructure model constructor.
     * @property {module:model/DomainPlotStructure}
     */
    DomainPlotStructure,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Holdings model constructor.
     * @property {module:model/Holdings}
     */
    Holdings,

    /**
     * The Household model constructor.
     * @property {module:model/Household}
     */
    Household,

    /**
     * The HouseholdCaps model constructor.
     * @property {module:model/HouseholdCaps}
     */
    HouseholdCaps,

    /**
     * The HouseholdSustenance model constructor.
     * @property {module:model/HouseholdSustenance}
     */
    HouseholdSustenance,

    /**
     * The Inventory model constructor.
     * @property {module:model/Inventory}
     */
    Inventory,

    /**
     * The InventoryAccount model constructor.
     * @property {module:model/InventoryAccount}
     */
    InventoryAccount,

    /**
     * The InventoryAssets model constructor.
     * @property {module:model/InventoryAssets}
     */
    InventoryAssets,

    /**
     * The InventoryFlows model constructor.
     * @property {module:model/InventoryFlows}
     */
    InventoryFlows,

    /**
     * The InventoryPastFlows model constructor.
     * @property {module:model/InventoryPastFlows}
     */
    InventoryPastFlows,

    /**
     * The Location model constructor.
     * @property {module:model/Location}
     */
    Location,

    /**
     * The MapRegion model constructor.
     * @property {module:model/MapRegion}
     */
    MapRegion,

    /**
     * The Player model constructor.
     * @property {module:model/Player}
     */
    Player,

    /**
     * The PlayerActivity model constructor.
     * @property {module:model/PlayerActivity}
     */
    PlayerActivity,

    /**
     * The PlayerSettings model constructor.
     * @property {module:model/PlayerSettings}
     */
    PlayerSettings,

    /**
     * The PlayerSettingsEmail model constructor.
     * @property {module:model/PlayerSettingsEmail}
     */
    PlayerSettingsEmail,

    /**
     * The PlayerSettingsNotifications model constructor.
     * @property {module:model/PlayerSettingsNotifications}
     */
    PlayerSettingsNotifications,

    /**
     * The PrestigeImpact model constructor.
     * @property {module:model/PrestigeImpact}
     */
    PrestigeImpact,

    /**
     * The ProductAsset model constructor.
     * @property {module:model/ProductAsset}
     */
    ProductAsset,

    /**
     * The ProductFlow model constructor.
     * @property {module:model/ProductFlow}
     */
    ProductFlow,

    /**
     * The ProductHolding model constructor.
     * @property {module:model/ProductHolding}
     */
    ProductHolding,

    /**
     * The ProductManager model constructor.
     * @property {module:model/ProductManager}
     */
    ProductManager,

    /**
     * The ProductPastFlow model constructor.
     * @property {module:model/ProductPastFlow}
     */
    ProductPastFlow,

    /**
     * The Specialization model constructor.
     * @property {module:model/Specialization}
     */
    Specialization,

    /**
     * The SpecializationPoints model constructor.
     * @property {module:model/SpecializationPoints}
     */
    SpecializationPoints,

    /**
     * The Town model constructor.
     * @property {module:model/Town}
     */
    Town,

    /**
     * The TownChurch model constructor.
     * @property {module:model/TownChurch}
     */
    TownChurch,

    /**
     * The TownCommoners model constructor.
     * @property {module:model/TownCommoners}
     */
    TownCommoners,

    /**
     * The TownCommonersIncome model constructor.
     * @property {module:model/TownCommonersIncome}
     */
    TownCommonersIncome,

    /**
     * The TownCommonersIncomeItems model constructor.
     * @property {module:model/TownCommonersIncomeItems}
     */
    TownCommonersIncomeItems,

    /**
     * The TownCommonersSpending model constructor.
     * @property {module:model/TownCommonersSpending}
     */
    TownCommonersSpending,

    /**
     * The TownCulture model constructor.
     * @property {module:model/TownCulture}
     */
    TownCulture,

    /**
     * The TownDomain model constructor.
     * @property {module:model/TownDomain}
     */
    TownDomain,

    /**
     * The TownGovernment model constructor.
     * @property {module:model/TownGovernment}
     */
    TownGovernment,

    /**
     * The TownGovernmentSpending model constructor.
     * @property {module:model/TownGovernmentSpending}
     */
    TownGovernmentSpending,

    /**
     * The TownGovernmentTaxesCollected model constructor.
     * @property {module:model/TownGovernmentTaxesCollected}
     */
    TownGovernmentTaxesCollected,

    /**
     * The TownNavigationZones model constructor.
     * @property {module:model/TownNavigationZones}
     */
    TownNavigationZones,

    /**
     * The TownSimple model constructor.
     * @property {module:model/TownSimple}
     */
    TownSimple,

    /**
     * The TownState model constructor.
     * @property {module:model/TownState}
     */
    TownState,

    /**
     * The Worker model constructor.
     * @property {module:model/Worker}
     */
    Worker,

    /**
     * The WorkerSkills model constructor.
     * @property {module:model/WorkerSkills}
     */
    WorkerSkills,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
