/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Building from './model/Building';
import BuildingConstruction from './model/BuildingConstruction';
import BuildingConstructionSettings from './model/BuildingConstructionSettings';
import BuildingDeliveryCost from './model/BuildingDeliveryCost';
import BuildingLocation from './model/BuildingLocation';
import BuildingProducer from './model/BuildingProducer';
import BuildingProducerPreviousOperation from './model/BuildingProducerPreviousOperation';
import Error from './model/Error';
import Holdings from './model/Holdings';
import Household from './model/Household';
import HouseholdCaps from './model/HouseholdCaps';
import HouseholdPrestigeImpactsInner from './model/HouseholdPrestigeImpactsInner';
import HouseholdSustenance from './model/HouseholdSustenance';
import Inventory from './model/Inventory';
import InventoryAccount from './model/InventoryAccount';
import InventoryAssets from './model/InventoryAssets';
import InventoryAssetsAlembics from './model/InventoryAssetsAlembics';
import InventoryFlows from './model/InventoryFlows';
import InventoryFlowsAlembics from './model/InventoryFlowsAlembics';
import InventoryPastFlows from './model/InventoryPastFlows';
import Player from './model/Player';
import PlayerActivity from './model/PlayerActivity';
import PlayerSettings from './model/PlayerSettings';
import PlayerSettingsEmail from './model/PlayerSettingsEmail';
import PlayerSettingsNotifications from './model/PlayerSettingsNotifications';
import ProductFlow from './model/ProductFlow';
import ProductHolding from './model/ProductHolding';
import ProductManager from './model/ProductManager';
import Specialization from './model/Specialization';
import SpecializationPoints from './model/SpecializationPoints';
import Worker from './model/Worker';
import WorkerSkills from './model/WorkerSkills';
import DefaultApi from './api/DefaultApi';


/**
* Mercatorio.js is a library that provides a easier way to interact with the Mercatorio API, allowing developers to make more third party applications and tools for the Mercatorio ecosystem..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var mercatorio-js = require('index'); // See note below*.
* var xxxSvc = new mercatorio-js.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new mercatorio-js.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new mercatorio-js.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new mercatorio-js.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Building model constructor.
     * @property {module:model/Building}
     */
    Building,

    /**
     * The BuildingConstruction model constructor.
     * @property {module:model/BuildingConstruction}
     */
    BuildingConstruction,

    /**
     * The BuildingConstructionSettings model constructor.
     * @property {module:model/BuildingConstructionSettings}
     */
    BuildingConstructionSettings,

    /**
     * The BuildingDeliveryCost model constructor.
     * @property {module:model/BuildingDeliveryCost}
     */
    BuildingDeliveryCost,

    /**
     * The BuildingLocation model constructor.
     * @property {module:model/BuildingLocation}
     */
    BuildingLocation,

    /**
     * The BuildingProducer model constructor.
     * @property {module:model/BuildingProducer}
     */
    BuildingProducer,

    /**
     * The BuildingProducerPreviousOperation model constructor.
     * @property {module:model/BuildingProducerPreviousOperation}
     */
    BuildingProducerPreviousOperation,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Holdings model constructor.
     * @property {module:model/Holdings}
     */
    Holdings,

    /**
     * The Household model constructor.
     * @property {module:model/Household}
     */
    Household,

    /**
     * The HouseholdCaps model constructor.
     * @property {module:model/HouseholdCaps}
     */
    HouseholdCaps,

    /**
     * The HouseholdPrestigeImpactsInner model constructor.
     * @property {module:model/HouseholdPrestigeImpactsInner}
     */
    HouseholdPrestigeImpactsInner,

    /**
     * The HouseholdSustenance model constructor.
     * @property {module:model/HouseholdSustenance}
     */
    HouseholdSustenance,

    /**
     * The Inventory model constructor.
     * @property {module:model/Inventory}
     */
    Inventory,

    /**
     * The InventoryAccount model constructor.
     * @property {module:model/InventoryAccount}
     */
    InventoryAccount,

    /**
     * The InventoryAssets model constructor.
     * @property {module:model/InventoryAssets}
     */
    InventoryAssets,

    /**
     * The InventoryAssetsAlembics model constructor.
     * @property {module:model/InventoryAssetsAlembics}
     */
    InventoryAssetsAlembics,

    /**
     * The InventoryFlows model constructor.
     * @property {module:model/InventoryFlows}
     */
    InventoryFlows,

    /**
     * The InventoryFlowsAlembics model constructor.
     * @property {module:model/InventoryFlowsAlembics}
     */
    InventoryFlowsAlembics,

    /**
     * The InventoryPastFlows model constructor.
     * @property {module:model/InventoryPastFlows}
     */
    InventoryPastFlows,

    /**
     * The Player model constructor.
     * @property {module:model/Player}
     */
    Player,

    /**
     * The PlayerActivity model constructor.
     * @property {module:model/PlayerActivity}
     */
    PlayerActivity,

    /**
     * The PlayerSettings model constructor.
     * @property {module:model/PlayerSettings}
     */
    PlayerSettings,

    /**
     * The PlayerSettingsEmail model constructor.
     * @property {module:model/PlayerSettingsEmail}
     */
    PlayerSettingsEmail,

    /**
     * The PlayerSettingsNotifications model constructor.
     * @property {module:model/PlayerSettingsNotifications}
     */
    PlayerSettingsNotifications,

    /**
     * The ProductFlow model constructor.
     * @property {module:model/ProductFlow}
     */
    ProductFlow,

    /**
     * The ProductHolding model constructor.
     * @property {module:model/ProductHolding}
     */
    ProductHolding,

    /**
     * The ProductManager model constructor.
     * @property {module:model/ProductManager}
     */
    ProductManager,

    /**
     * The Specialization model constructor.
     * @property {module:model/Specialization}
     */
    Specialization,

    /**
     * The SpecializationPoints model constructor.
     * @property {module:model/SpecializationPoints}
     */
    SpecializationPoints,

    /**
     * The Worker model constructor.
     * @property {module:model/Worker}
     */
    Worker,

    /**
     * The WorkerSkills model constructor.
     * @property {module:model/WorkerSkills}
     */
    WorkerSkills,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
