/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BuildingPreviousOperation model module.
 * @module model/BuildingPreviousOperation
 * @version 1.0.0
 */
class BuildingPreviousOperation {
    /**
     * Constructs a new <code>BuildingPreviousOperation</code>.
     * @alias module:model/BuildingPreviousOperation
     */
    constructor() { 
        
        BuildingPreviousOperation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BuildingPreviousOperation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BuildingPreviousOperation} obj Optional instance to populate.
     * @return {module:model/BuildingPreviousOperation} The populated <code>BuildingPreviousOperation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BuildingPreviousOperation();

            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('production')) {
                obj['production'] = ApiClient.convertToType(data['production'], 'String');
            }
            if (data.hasOwnProperty('turns')) {
                obj['turns'] = ApiClient.convertToType(data['turns'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BuildingPreviousOperation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BuildingPreviousOperation</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['target'] && !(typeof data['target'] === 'string' || data['target'] instanceof String)) {
            throw new Error("Expected the field `target` to be a primitive type in the JSON string but got " + data['target']);
        }
        // ensure the json data is a string
        if (data['production'] && !(typeof data['production'] === 'string' || data['production'] instanceof String)) {
            throw new Error("Expected the field `production` to be a primitive type in the JSON string but got " + data['production']);
        }

        return true;
    }


}



/**
 * @member {String} target
 */
BuildingPreviousOperation.prototype['target'] = undefined;

/**
 * @member {String} production
 */
BuildingPreviousOperation.prototype['production'] = undefined;

/**
 * @member {Number} turns
 */
BuildingPreviousOperation.prototype['turns'] = undefined;






export default BuildingPreviousOperation;

