/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConstructionSettings model module.
 * @module model/ConstructionSettings
 * @version 1.0.0
 */
class ConstructionSettings {
    /**
     * Constructs a new <code>ConstructionSettings</code>.
     * @alias module:model/ConstructionSettings
     */
    constructor() { 
        
        ConstructionSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConstructionSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConstructionSettings} obj Optional instance to populate.
     * @return {module:model/ConstructionSettings} The populated <code>ConstructionSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConstructionSettings();

            if (data.hasOwnProperty('honour_low_stock')) {
                obj['honour_low_stock'] = ApiClient.convertToType(data['honour_low_stock'], 'Boolean');
            }
            if (data.hasOwnProperty('pace')) {
                obj['pace'] = ApiClient.convertToType(data['pace'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConstructionSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConstructionSettings</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} honour_low_stock
 */
ConstructionSettings.prototype['honour_low_stock'] = undefined;

/**
 * @member {Number} pace
 */
ConstructionSettings.prototype['pace'] = undefined;






export default ConstructionSettings;

