/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DomainPlotStructure from './DomainPlotStructure';

/**
 * The DomainPlot model module.
 * @module model/DomainPlot
 * @version 1.0.0
 */
class DomainPlot {
    /**
     * Constructs a new <code>DomainPlot</code>.
     * @alias module:model/DomainPlot
     */
    constructor() { 
        
        DomainPlot.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DomainPlot</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DomainPlot} obj Optional instance to populate.
     * @return {module:model/DomainPlot} The populated <code>DomainPlot</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DomainPlot();

            if (data.hasOwnProperty('owner_id')) {
                obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'String');
            }
            if (data.hasOwnProperty('structure')) {
                obj['structure'] = DomainPlotStructure.constructFromObject(data['structure']);
            }
            if (data.hasOwnProperty('resource')) {
                obj['resource'] = ApiClient.convertToType(data['resource'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DomainPlot</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DomainPlot</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['owner_id'] && !(typeof data['owner_id'] === 'string' || data['owner_id'] instanceof String)) {
            throw new Error("Expected the field `owner_id` to be a primitive type in the JSON string but got " + data['owner_id']);
        }
        // validate the optional field `structure`
        if (data['structure']) { // data not null
          DomainPlotStructure.validateJSON(data['structure']);
        }

        return true;
    }


}



/**
 * @member {String} owner_id
 */
DomainPlot.prototype['owner_id'] = undefined;

/**
 * @member {module:model/DomainPlotStructure} structure
 */
DomainPlot.prototype['structure'] = undefined;

/**
 * @member {Number} resource
 */
DomainPlot.prototype['resource'] = undefined;






export default DomainPlot;

