/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HouseholdCaps model module.
 * @module model/HouseholdCaps
 * @version 1.0.0
 */
class HouseholdCaps {
    /**
     * Constructs a new <code>HouseholdCaps</code>.
     * @alias module:model/HouseholdCaps
     */
    constructor() { 
        
        HouseholdCaps.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HouseholdCaps</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HouseholdCaps} obj Optional instance to populate.
     * @return {module:model/HouseholdCaps} The populated <code>HouseholdCaps</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HouseholdCaps();

            if (data.hasOwnProperty('transports')) {
                obj['transports'] = ApiClient.convertToType(data['transports'], 'Number');
            }
            if (data.hasOwnProperty('regular_management')) {
                obj['regular_management'] = ApiClient.convertToType(data['regular_management'], 'Number');
            }
            if (data.hasOwnProperty('prestige_management')) {
                obj['prestige_management'] = ApiClient.convertToType(data['prestige_management'], 'Number');
            }
            if (data.hasOwnProperty('tenants')) {
                obj['tenants'] = ApiClient.convertToType(data['tenants'], 'Number');
            }
            if (data.hasOwnProperty('apprentices')) {
                obj['apprentices'] = ApiClient.convertToType(data['apprentices'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HouseholdCaps</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HouseholdCaps</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} transports
 */
HouseholdCaps.prototype['transports'] = undefined;

/**
 * @member {Number} regular_management
 */
HouseholdCaps.prototype['regular_management'] = undefined;

/**
 * @member {Number} prestige_management
 */
HouseholdCaps.prototype['prestige_management'] = undefined;

/**
 * @member {Number} tenants
 */
HouseholdCaps.prototype['tenants'] = undefined;

/**
 * @member {Number} apprentices
 */
HouseholdCaps.prototype['apprentices'] = undefined;






export default HouseholdCaps;

