/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HouseholdSpecializationPoints from './HouseholdSpecializationPoints';

/**
 * The HouseholdSpecialization model module.
 * @module model/HouseholdSpecialization
 * @version 1.0.0
 */
class HouseholdSpecialization {
    /**
     * Constructs a new <code>HouseholdSpecialization</code>.
     * @alias module:model/HouseholdSpecialization
     */
    constructor() { 
        
        HouseholdSpecialization.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HouseholdSpecialization</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HouseholdSpecialization} obj Optional instance to populate.
     * @return {module:model/HouseholdSpecialization} The populated <code>HouseholdSpecialization</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HouseholdSpecialization();

            if (data.hasOwnProperty('points')) {
                obj['points'] = HouseholdSpecializationPoints.constructFromObject(data['points']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HouseholdSpecialization</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HouseholdSpecialization</code>.
     */
    static validateJSON(data) {
        // validate the optional field `points`
        if (data['points']) { // data not null
          HouseholdSpecializationPoints.validateJSON(data['points']);
        }

        return true;
    }


}



/**
 * @member {module:model/HouseholdSpecializationPoints} points
 */
HouseholdSpecialization.prototype['points'] = undefined;






export default HouseholdSpecialization;

