/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InventoryFlowsProductNameProjection model module.
 * @module model/InventoryFlowsProductNameProjection
 * @version 1.0.0
 */
class InventoryFlowsProductNameProjection {
    /**
     * Constructs a new <code>InventoryFlowsProductNameProjection</code>.
     * @alias module:model/InventoryFlowsProductNameProjection
     */
    constructor() { 
        
        InventoryFlowsProductNameProjection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InventoryFlowsProductNameProjection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InventoryFlowsProductNameProjection} obj Optional instance to populate.
     * @return {module:model/InventoryFlowsProductNameProjection} The populated <code>InventoryFlowsProductNameProjection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InventoryFlowsProductNameProjection();

            if (data.hasOwnProperty('consumption')) {
                obj['consumption'] = ApiClient.convertToType(data['consumption'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InventoryFlowsProductNameProjection</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InventoryFlowsProductNameProjection</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['consumption'] && !(typeof data['consumption'] === 'string' || data['consumption'] instanceof String)) {
            throw new Error("Expected the field `consumption` to be a primitive type in the JSON string but got " + data['consumption']);
        }

        return true;
    }


}



/**
 * @member {String} consumption
 */
InventoryFlowsProductNameProjection.prototype['consumption'] = undefined;






export default InventoryFlowsProductNameProjection;

