/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryFlowsProductNameProjection from './InventoryFlowsProductNameProjection';

/**
 * The InventoryFlowsProductName model module.
 * @module model/InventoryFlowsProductName
 * @version 1.0.0
 */
class InventoryFlowsProductName {
    /**
     * Constructs a new <code>InventoryFlowsProductName</code>.
     * @alias module:model/InventoryFlowsProductName
     */
    constructor() { 
        
        InventoryFlowsProductName.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InventoryFlowsProductName</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InventoryFlowsProductName} obj Optional instance to populate.
     * @return {module:model/InventoryFlowsProductName} The populated <code>InventoryFlowsProductName</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InventoryFlowsProductName();

            if (data.hasOwnProperty('projection')) {
                obj['projection'] = InventoryFlowsProductNameProjection.constructFromObject(data['projection']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InventoryFlowsProductName</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InventoryFlowsProductName</code>.
     */
    static validateJSON(data) {
        // validate the optional field `projection`
        if (data['projection']) { // data not null
          InventoryFlowsProductNameProjection.validateJSON(data['projection']);
        }

        return true;
    }


}



/**
 * @member {module:model/InventoryFlowsProductNameProjection} projection
 */
InventoryFlowsProductName.prototype['projection'] = undefined;






export default InventoryFlowsProductName;

