/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryAccount from './InventoryAccount';
import InventoryFlows from './InventoryFlows';
import InventoryPreviousFlows from './InventoryPreviousFlows';
import ProductsHoldings from './ProductsHoldings';

/**
 * The Inventory model module.
 * @module model/Inventory
 * @version 1.0.0
 */
class Inventory {
    /**
     * Constructs a new <code>Inventory</code>.
     * @alias module:model/Inventory
     */
    constructor() { 
        
        Inventory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Inventory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Inventory} obj Optional instance to populate.
     * @return {module:model/Inventory} The populated <code>Inventory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Inventory();

            if (data.hasOwnProperty('account')) {
                obj['account'] = InventoryAccount.constructFromObject(data['account']);
            }
            if (data.hasOwnProperty('capacity')) {
                obj['capacity'] = ApiClient.convertToType(data['capacity'], 'Number');
            }
            if (data.hasOwnProperty('holdings')) {
                obj['holdings'] = ProductsHoldings.constructFromObject(data['holdings']);
            }
            if (data.hasOwnProperty('flows')) {
                obj['flows'] = InventoryFlows.constructFromObject(data['flows']);
            }
            if (data.hasOwnProperty('previous_flows')) {
                obj['previous_flows'] = InventoryPreviousFlows.constructFromObject(data['previous_flows']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Inventory</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Inventory</code>.
     */
    static validateJSON(data) {
        // validate the optional field `account`
        if (data['account']) { // data not null
          InventoryAccount.validateJSON(data['account']);
        }
        // validate the optional field `holdings`
        if (data['holdings']) { // data not null
          ProductsHoldings.validateJSON(data['holdings']);
        }
        // validate the optional field `flows`
        if (data['flows']) { // data not null
          InventoryFlows.validateJSON(data['flows']);
        }
        // validate the optional field `previous_flows`
        if (data['previous_flows']) { // data not null
          InventoryPreviousFlows.validateJSON(data['previous_flows']);
        }

        return true;
    }


}



/**
 * @member {module:model/InventoryAccount} account
 */
Inventory.prototype['account'] = undefined;

/**
 * @member {Number} capacity
 */
Inventory.prototype['capacity'] = undefined;

/**
 * @member {module:model/ProductsHoldings} holdings
 */
Inventory.prototype['holdings'] = undefined;

/**
 * @member {module:model/InventoryFlows} flows
 */
Inventory.prototype['flows'] = undefined;

/**
 * @member {module:model/InventoryPreviousFlows} previous_flows
 */
Inventory.prototype['previous_flows'] = undefined;






export default Inventory;

