/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryFlowsProductName from './InventoryFlowsProductName';

/**
 * The InventoryFlows model module.
 * @module model/InventoryFlows
 * @version 1.0.0
 */
class InventoryFlows {
    /**
     * Constructs a new <code>InventoryFlows</code>.
     * @alias module:model/InventoryFlows
     */
    constructor() { 
        
        InventoryFlows.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InventoryFlows</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InventoryFlows} obj Optional instance to populate.
     * @return {module:model/InventoryFlows} The populated <code>InventoryFlows</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InventoryFlows();

            if (data.hasOwnProperty('ProductName')) {
                obj['ProductName'] = InventoryFlowsProductName.constructFromObject(data['ProductName']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InventoryFlows</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InventoryFlows</code>.
     */
    static validateJSON(data) {
        // validate the optional field `ProductName`
        if (data['ProductName']) { // data not null
          InventoryFlowsProductName.validateJSON(data['ProductName']);
        }

        return true;
    }


}



/**
 * @member {module:model/InventoryFlowsProductName} ProductName
 */
InventoryFlows.prototype['ProductName'] = undefined;






export default InventoryFlows;

