/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlayerSettingsNotifications model module.
 * @module model/PlayerSettingsNotifications
 * @version 1.0.0
 */
class PlayerSettingsNotifications {
    /**
     * Constructs a new <code>PlayerSettingsNotifications</code>.
     * @alias module:model/PlayerSettingsNotifications
     */
    constructor() { 
        
        PlayerSettingsNotifications.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlayerSettingsNotifications</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlayerSettingsNotifications} obj Optional instance to populate.
     * @return {module:model/PlayerSettingsNotifications} The populated <code>PlayerSettingsNotifications</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlayerSettingsNotifications();

            if (data.hasOwnProperty('discord')) {
                obj['discord'] = ApiClient.convertToType(data['discord'], 'Boolean');
            }
            if (data.hasOwnProperty('mutes')) {
                obj['mutes'] = ApiClient.convertToType(data['mutes'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PlayerSettingsNotifications</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PlayerSettingsNotifications</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} discord
 */
PlayerSettingsNotifications.prototype['discord'] = undefined;

/**
 * @member {Object} mutes
 */
PlayerSettingsNotifications.prototype['mutes'] = undefined;






export default PlayerSettingsNotifications;

