/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlayerSettingsEmail from './PlayerSettingsEmail';
import PlayerSettingsNotifications from './PlayerSettingsNotifications';

/**
 * The PlayerSettings model module.
 * @module model/PlayerSettings
 * @version 1.0.0
 */
class PlayerSettings {
    /**
     * Constructs a new <code>PlayerSettings</code>.
     * @alias module:model/PlayerSettings
     */
    constructor() { 
        
        PlayerSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlayerSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlayerSettings} obj Optional instance to populate.
     * @return {module:model/PlayerSettings} The populated <code>PlayerSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlayerSettings();

            if (data.hasOwnProperty('sound_volume')) {
                obj['sound_volume'] = ApiClient.convertToType(data['sound_volume'], 'Number');
            }
            if (data.hasOwnProperty('notifications')) {
                obj['notifications'] = PlayerSettingsNotifications.constructFromObject(data['notifications']);
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = PlayerSettingsEmail.constructFromObject(data['email']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PlayerSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PlayerSettings</code>.
     */
    static validateJSON(data) {
        // validate the optional field `notifications`
        if (data['notifications']) { // data not null
          PlayerSettingsNotifications.validateJSON(data['notifications']);
        }
        // validate the optional field `email`
        if (data['email']) { // data not null
          PlayerSettingsEmail.validateJSON(data['email']);
        }

        return true;
    }


}



/**
 * @member {Number} sound_volume
 */
PlayerSettings.prototype['sound_volume'] = undefined;

/**
 * @member {module:model/PlayerSettingsNotifications} notifications
 */
PlayerSettings.prototype['notifications'] = undefined;

/**
 * @member {module:model/PlayerSettingsEmail} email
 */
PlayerSettings.prototype['email'] = undefined;






export default PlayerSettings;

