/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PrestigeImpact model module.
 * @module model/PrestigeImpact
 * @version 1.0.0
 */
class PrestigeImpact {
    /**
     * Constructs a new <code>PrestigeImpact</code>.
     * @alias module:model/PrestigeImpact
     */
    constructor() { 
        
        PrestigeImpact.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PrestigeImpact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PrestigeImpact} obj Optional instance to populate.
     * @return {module:model/PrestigeImpact} The populated <code>PrestigeImpact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PrestigeImpact();

            if (data.hasOwnProperty('factor')) {
                obj['factor'] = ApiClient.convertToType(data['factor'], 'String');
            }
            if (data.hasOwnProperty('impact')) {
                obj['impact'] = ApiClient.convertToType(data['impact'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PrestigeImpact</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PrestigeImpact</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['factor'] && !(typeof data['factor'] === 'string' || data['factor'] instanceof String)) {
            throw new Error("Expected the field `factor` to be a primitive type in the JSON string but got " + data['factor']);
        }
        // ensure the json data is a string
        if (data['impact'] && !(typeof data['impact'] === 'string' || data['impact'] instanceof String)) {
            throw new Error("Expected the field `impact` to be a primitive type in the JSON string but got " + data['impact']);
        }

        return true;
    }


}



/**
 * @member {String} factor
 */
PrestigeImpact.prototype['factor'] = undefined;

/**
 * @member {String} impact
 */
PrestigeImpact.prototype['impact'] = undefined;






export default PrestigeImpact;

