/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductManager from './ProductManager';

/**
 * The ProductsHoldingsAlembics model module.
 * @module model/ProductsHoldingsAlembics
 * @version 1.0.0
 */
class ProductsHoldingsAlembics {
    /**
     * Constructs a new <code>ProductsHoldingsAlembics</code>.
     * @alias module:model/ProductsHoldingsAlembics
     */
    constructor() { 
        
        ProductsHoldingsAlembics.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductsHoldingsAlembics</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductsHoldingsAlembics} obj Optional instance to populate.
     * @return {module:model/ProductsHoldingsAlembics} The populated <code>ProductsHoldingsAlembics</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductsHoldingsAlembics();

            if (data.hasOwnProperty('managers')) {
                obj['managers'] = ProductManager.constructFromObject(data['managers']);
            }
            if (data.hasOwnProperty('capacity')) {
                obj['capacity'] = ApiClient.convertToType(data['capacity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductsHoldingsAlembics</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductsHoldingsAlembics</code>.
     */
    static validateJSON(data) {
        // validate the optional field `managers`
        if (data['managers']) { // data not null
          ProductManager.validateJSON(data['managers']);
        }

        return true;
    }


}



/**
 * @member {module:model/ProductManager} managers
 */
ProductsHoldingsAlembics.prototype['managers'] = undefined;

/**
 * @member {Number} capacity
 */
ProductsHoldingsAlembics.prototype['capacity'] = undefined;






export default ProductsHoldingsAlembics;

