/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductManager model module.
 * @module model/ProductManager
 * @version 1.0.0
 */
class ProductManager {
    /**
     * Constructs a new <code>ProductManager</code>.
     * @alias module:model/ProductManager
     */
    constructor() { 
        
        ProductManager.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductManager</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductManager} obj Optional instance to populate.
     * @return {module:model/ProductManager} The populated <code>ProductManager</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductManager();

            if (data.hasOwnProperty('max_holding')) {
                obj['max_holding'] = ApiClient.convertToType(data['max_holding'], 'Number');
            }
            if (data.hasOwnProperty('min_holding')) {
                obj['min_holding'] = ApiClient.convertToType(data['min_holding'], 'Number');
            }
            if (data.hasOwnProperty('buy_volume')) {
                obj['buy_volume'] = ApiClient.convertToType(data['buy_volume'], 'Number');
            }
            if (data.hasOwnProperty('buy_price')) {
                obj['buy_price'] = ApiClient.convertToType(data['buy_price'], 'String');
            }
            if (data.hasOwnProperty('sell_volume')) {
                obj['sell_volume'] = ApiClient.convertToType(data['sell_volume'], 'Number');
            }
            if (data.hasOwnProperty('sell_price')) {
                obj['sell_price'] = ApiClient.convertToType(data['sell_price'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductManager</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductManager</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['buy_price'] && !(typeof data['buy_price'] === 'string' || data['buy_price'] instanceof String)) {
            throw new Error("Expected the field `buy_price` to be a primitive type in the JSON string but got " + data['buy_price']);
        }
        // ensure the json data is a string
        if (data['sell_price'] && !(typeof data['sell_price'] === 'string' || data['sell_price'] instanceof String)) {
            throw new Error("Expected the field `sell_price` to be a primitive type in the JSON string but got " + data['sell_price']);
        }

        return true;
    }


}



/**
 * @member {Number} max_holding
 */
ProductManager.prototype['max_holding'] = undefined;

/**
 * @member {Number} min_holding
 */
ProductManager.prototype['min_holding'] = undefined;

/**
 * @member {Number} buy_volume
 */
ProductManager.prototype['buy_volume'] = undefined;

/**
 * @member {String} buy_price
 */
ProductManager.prototype['buy_price'] = undefined;

/**
 * @member {Number} sell_volume
 */
ProductManager.prototype['sell_volume'] = undefined;

/**
 * @member {String} sell_price
 */
ProductManager.prototype['sell_price'] = undefined;






export default ProductManager;

