/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TownGovernmentTaxesCollected model module.
 * @module model/TownGovernmentTaxesCollected
 * @version 1.0.0
 */
class TownGovernmentTaxesCollected {
    /**
     * Constructs a new <code>TownGovernmentTaxesCollected</code>.
     * @alias module:model/TownGovernmentTaxesCollected
     */
    constructor() { 
        
        TownGovernmentTaxesCollected.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TownGovernmentTaxesCollected</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TownGovernmentTaxesCollected} obj Optional instance to populate.
     * @return {module:model/TownGovernmentTaxesCollected} The populated <code>TownGovernmentTaxesCollected</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TownGovernmentTaxesCollected();

            if (data.hasOwnProperty('payments')) {
                obj['payments'] = ApiClient.convertToType(data['payments'], 'String');
            }
            if (data.hasOwnProperty('land_tax')) {
                obj['land_tax'] = ApiClient.convertToType(data['land_tax'], 'String');
            }
            if (data.hasOwnProperty('structure_tax')) {
                obj['structure_tax'] = ApiClient.convertToType(data['structure_tax'], 'String');
            }
            if (data.hasOwnProperty('delivery_fees')) {
                obj['delivery_fees'] = ApiClient.convertToType(data['delivery_fees'], 'String');
            }
            if (data.hasOwnProperty('transport_fees')) {
                obj['transport_fees'] = ApiClient.convertToType(data['transport_fees'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TownGovernmentTaxesCollected</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TownGovernmentTaxesCollected</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['payments'] && !(typeof data['payments'] === 'string' || data['payments'] instanceof String)) {
            throw new Error("Expected the field `payments` to be a primitive type in the JSON string but got " + data['payments']);
        }
        // ensure the json data is a string
        if (data['land_tax'] && !(typeof data['land_tax'] === 'string' || data['land_tax'] instanceof String)) {
            throw new Error("Expected the field `land_tax` to be a primitive type in the JSON string but got " + data['land_tax']);
        }
        // ensure the json data is a string
        if (data['structure_tax'] && !(typeof data['structure_tax'] === 'string' || data['structure_tax'] instanceof String)) {
            throw new Error("Expected the field `structure_tax` to be a primitive type in the JSON string but got " + data['structure_tax']);
        }
        // ensure the json data is a string
        if (data['delivery_fees'] && !(typeof data['delivery_fees'] === 'string' || data['delivery_fees'] instanceof String)) {
            throw new Error("Expected the field `delivery_fees` to be a primitive type in the JSON string but got " + data['delivery_fees']);
        }
        // ensure the json data is a string
        if (data['transport_fees'] && !(typeof data['transport_fees'] === 'string' || data['transport_fees'] instanceof String)) {
            throw new Error("Expected the field `transport_fees` to be a primitive type in the JSON string but got " + data['transport_fees']);
        }

        return true;
    }


}



/**
 * @member {String} payments
 */
TownGovernmentTaxesCollected.prototype['payments'] = undefined;

/**
 * @member {String} land_tax
 */
TownGovernmentTaxesCollected.prototype['land_tax'] = undefined;

/**
 * @member {String} structure_tax
 */
TownGovernmentTaxesCollected.prototype['structure_tax'] = undefined;

/**
 * @member {String} delivery_fees
 */
TownGovernmentTaxesCollected.prototype['delivery_fees'] = undefined;

/**
 * @member {String} transport_fees
 */
TownGovernmentTaxesCollected.prototype['transport_fees'] = undefined;






export default TownGovernmentTaxesCollected;

