/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TownCommonersIncomeItems model module.
 * @module model/TownCommonersIncomeItems
 * @version 1.0.0
 */
class TownCommonersIncomeItems {
    /**
     * Constructs a new <code>TownCommonersIncomeItems</code>.
     * @alias module:model/TownCommonersIncomeItems
     */
    constructor() { 
        
        TownCommonersIncomeItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TownCommonersIncomeItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TownCommonersIncomeItems} obj Optional instance to populate.
     * @return {module:model/TownCommonersIncomeItems} The populated <code>TownCommonersIncomeItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TownCommonersIncomeItems();

            if (data.hasOwnProperty('product')) {
                obj['product'] = ApiClient.convertToType(data['product'], 'String');
            }
            if (data.hasOwnProperty('bonus')) {
                obj['bonus'] = ApiClient.convertToType(data['bonus'], 'String');
            }
            if (data.hasOwnProperty('desire')) {
                obj['desire'] = ApiClient.convertToType(data['desire'], 'String');
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = ApiClient.convertToType(data['request'], 'String');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'String');
            }
            if (data.hasOwnProperty('budget')) {
                obj['budget'] = ApiClient.convertToType(data['budget'], 'String');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TownCommonersIncomeItems</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TownCommonersIncomeItems</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['product'] && !(typeof data['product'] === 'string' || data['product'] instanceof String)) {
            throw new Error("Expected the field `product` to be a primitive type in the JSON string but got " + data['product']);
        }
        // ensure the json data is a string
        if (data['bonus'] && !(typeof data['bonus'] === 'string' || data['bonus'] instanceof String)) {
            throw new Error("Expected the field `bonus` to be a primitive type in the JSON string but got " + data['bonus']);
        }
        // ensure the json data is a string
        if (data['desire'] && !(typeof data['desire'] === 'string' || data['desire'] instanceof String)) {
            throw new Error("Expected the field `desire` to be a primitive type in the JSON string but got " + data['desire']);
        }
        // ensure the json data is a string
        if (data['request'] && !(typeof data['request'] === 'string' || data['request'] instanceof String)) {
            throw new Error("Expected the field `request` to be a primitive type in the JSON string but got " + data['request']);
        }
        // ensure the json data is a string
        if (data['result'] && !(typeof data['result'] === 'string' || data['result'] instanceof String)) {
            throw new Error("Expected the field `result` to be a primitive type in the JSON string but got " + data['result']);
        }
        // ensure the json data is a string
        if (data['budget'] && !(typeof data['budget'] === 'string' || data['budget'] instanceof String)) {
            throw new Error("Expected the field `budget` to be a primitive type in the JSON string but got " + data['budget']);
        }
        // ensure the json data is a string
        if (data['weight'] && !(typeof data['weight'] === 'string' || data['weight'] instanceof String)) {
            throw new Error("Expected the field `weight` to be a primitive type in the JSON string but got " + data['weight']);
        }

        return true;
    }


}



/**
 * @member {String} product
 */
TownCommonersIncomeItems.prototype['product'] = undefined;

/**
 * @member {String} bonus
 */
TownCommonersIncomeItems.prototype['bonus'] = undefined;

/**
 * @member {String} desire
 */
TownCommonersIncomeItems.prototype['desire'] = undefined;

/**
 * @member {String} request
 */
TownCommonersIncomeItems.prototype['request'] = undefined;

/**
 * @member {String} result
 */
TownCommonersIncomeItems.prototype['result'] = undefined;

/**
 * @member {String} budget
 */
TownCommonersIncomeItems.prototype['budget'] = undefined;

/**
 * @member {String} weight
 */
TownCommonersIncomeItems.prototype['weight'] = undefined;






export default TownCommonersIncomeItems;

