/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CommonersTownState from './CommonersTownState';
import TownCommonersIncome from './TownCommonersIncome';
import TownCommonersSpending from './TownCommonersSpending';

/**
 * The TownCommoners model module.
 * @module model/TownCommoners
 * @version 1.0.0
 */
class TownCommoners {
    /**
     * Constructs a new <code>TownCommoners</code>.
     * @alias module:model/TownCommoners
     */
    constructor() { 
        
        TownCommoners.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TownCommoners</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TownCommoners} obj Optional instance to populate.
     * @return {module:model/TownCommoners} The populated <code>TownCommoners</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TownCommoners();

            if (data.hasOwnProperty('account_id')) {
                obj['account_id'] = ApiClient.convertToType(data['account_id'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('migration')) {
                obj['migration'] = ApiClient.convertToType(data['migration'], 'String');
            }
            if (data.hasOwnProperty('income')) {
                obj['income'] = TownCommonersIncome.constructFromObject(data['income']);
            }
            if (data.hasOwnProperty('spending')) {
                obj['spending'] = ApiClient.convertToType(data['spending'], [TownCommonersSpending]);
            }
            if (data.hasOwnProperty('town_state')) {
                obj['town_state'] = CommonersTownState.constructFromObject(data['town_state']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TownCommoners</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TownCommoners</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['account_id'] && !(typeof data['account_id'] === 'string' || data['account_id'] instanceof String)) {
            throw new Error("Expected the field `account_id` to be a primitive type in the JSON string but got " + data['account_id']);
        }
        // ensure the json data is a string
        if (data['migration'] && !(typeof data['migration'] === 'string' || data['migration'] instanceof String)) {
            throw new Error("Expected the field `migration` to be a primitive type in the JSON string but got " + data['migration']);
        }
        // validate the optional field `income`
        if (data['income']) { // data not null
          TownCommonersIncome.validateJSON(data['income']);
        }
        if (data['spending']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['spending'])) {
                throw new Error("Expected the field `spending` to be an array in the JSON data but got " + data['spending']);
            }
            // validate the optional field `spending` (array)
            for (const item of data['spending']) {
                TownCommonersSpending.validateJSON(item);
            };
        }
        // validate the optional field `town_state`
        if (data['town_state']) { // data not null
          CommonersTownState.validateJSON(data['town_state']);
        }

        return true;
    }


}



/**
 * @member {String} account_id
 */
TownCommoners.prototype['account_id'] = undefined;

/**
 * @member {Number} count
 */
TownCommoners.prototype['count'] = undefined;

/**
 * @member {String} migration
 */
TownCommoners.prototype['migration'] = undefined;

/**
 * @member {module:model/TownCommonersIncome} income
 */
TownCommoners.prototype['income'] = undefined;

/**
 * @member {Array.<module:model/TownCommonersSpending>} spending
 */
TownCommoners.prototype['spending'] = undefined;

/**
 * @member {module:model/CommonersTownState} town_state
 */
TownCommoners.prototype['town_state'] = undefined;






export default TownCommoners;

