/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TownNavigationZones model module.
 * @module model/TownNavigationZones
 * @version 1.0.0
 */
class TownNavigationZones {
    /**
     * Constructs a new <code>TownNavigationZones</code>.
     * @alias module:model/TownNavigationZones
     */
    constructor() { 
        
        TownNavigationZones.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TownNavigationZones</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TownNavigationZones} obj Optional instance to populate.
     * @return {module:model/TownNavigationZones} The populated <code>TownNavigationZones</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TownNavigationZones();

            if (data.hasOwnProperty('NavigationZoneID1')) {
                obj['NavigationZoneID1'] = ApiClient.convertToType(data['NavigationZoneID1'], 'Number');
            }
            if (data.hasOwnProperty('NavigationZoneID2')) {
                obj['NavigationZoneID2'] = ApiClient.convertToType(data['NavigationZoneID2'], 'Number');
            }
            if (data.hasOwnProperty('NavigationZoneID3')) {
                obj['NavigationZoneID3'] = ApiClient.convertToType(data['NavigationZoneID3'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TownNavigationZones</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TownNavigationZones</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} NavigationZoneID1
 */
TownNavigationZones.prototype['NavigationZoneID1'] = undefined;

/**
 * @member {Number} NavigationZoneID2
 */
TownNavigationZones.prototype['NavigationZoneID2'] = undefined;

/**
 * @member {Number} NavigationZoneID3
 */
TownNavigationZones.prototype['NavigationZoneID3'] = undefined;






export default TownNavigationZones;

