/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TownCulture model module.
 * @module model/TownCulture
 * @version 1.0.0
 */
class TownCulture {
    /**
     * Constructs a new <code>TownCulture</code>.
     * @alias module:model/TownCulture
     */
    constructor() { 
        
        TownCulture.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TownCulture</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TownCulture} obj Optional instance to populate.
     * @return {module:model/TownCulture} The populated <code>TownCulture</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TownCulture();

            if (data.hasOwnProperty('nutrition')) {
                obj['nutrition'] = ApiClient.convertToType(data['nutrition'], 'String');
            }
            if (data.hasOwnProperty('textile')) {
                obj['textile'] = ApiClient.convertToType(data['textile'], 'String');
            }
            if (data.hasOwnProperty('crafting')) {
                obj['crafting'] = ApiClient.convertToType(data['crafting'], 'String');
            }
            if (data.hasOwnProperty('forging')) {
                obj['forging'] = ApiClient.convertToType(data['forging'], 'String');
            }
            if (data.hasOwnProperty('weaponry')) {
                obj['weaponry'] = ApiClient.convertToType(data['weaponry'], 'String');
            }
            if (data.hasOwnProperty('maritime')) {
                obj['maritime'] = ApiClient.convertToType(data['maritime'], 'String');
            }
            if (data.hasOwnProperty('mercantile')) {
                obj['mercantile'] = ApiClient.convertToType(data['mercantile'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TownCulture</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TownCulture</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['nutrition'] && !(typeof data['nutrition'] === 'string' || data['nutrition'] instanceof String)) {
            throw new Error("Expected the field `nutrition` to be a primitive type in the JSON string but got " + data['nutrition']);
        }
        // ensure the json data is a string
        if (data['textile'] && !(typeof data['textile'] === 'string' || data['textile'] instanceof String)) {
            throw new Error("Expected the field `textile` to be a primitive type in the JSON string but got " + data['textile']);
        }
        // ensure the json data is a string
        if (data['crafting'] && !(typeof data['crafting'] === 'string' || data['crafting'] instanceof String)) {
            throw new Error("Expected the field `crafting` to be a primitive type in the JSON string but got " + data['crafting']);
        }
        // ensure the json data is a string
        if (data['forging'] && !(typeof data['forging'] === 'string' || data['forging'] instanceof String)) {
            throw new Error("Expected the field `forging` to be a primitive type in the JSON string but got " + data['forging']);
        }
        // ensure the json data is a string
        if (data['weaponry'] && !(typeof data['weaponry'] === 'string' || data['weaponry'] instanceof String)) {
            throw new Error("Expected the field `weaponry` to be a primitive type in the JSON string but got " + data['weaponry']);
        }
        // ensure the json data is a string
        if (data['maritime'] && !(typeof data['maritime'] === 'string' || data['maritime'] instanceof String)) {
            throw new Error("Expected the field `maritime` to be a primitive type in the JSON string but got " + data['maritime']);
        }
        // ensure the json data is a string
        if (data['mercantile'] && !(typeof data['mercantile'] === 'string' || data['mercantile'] instanceof String)) {
            throw new Error("Expected the field `mercantile` to be a primitive type in the JSON string but got " + data['mercantile']);
        }

        return true;
    }


}



/**
 * @member {String} nutrition
 */
TownCulture.prototype['nutrition'] = undefined;

/**
 * @member {String} textile
 */
TownCulture.prototype['textile'] = undefined;

/**
 * @member {String} crafting
 */
TownCulture.prototype['crafting'] = undefined;

/**
 * @member {String} forging
 */
TownCulture.prototype['forging'] = undefined;

/**
 * @member {String} weaponry
 */
TownCulture.prototype['weaponry'] = undefined;

/**
 * @member {String} maritime
 */
TownCulture.prototype['maritime'] = undefined;

/**
 * @member {String} mercantile
 */
TownCulture.prototype['mercantile'] = undefined;






export default TownCulture;

