/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TownCommonersIncomeItems from './TownCommonersIncomeItems';

/**
 * The TownGovernmentSpending model module.
 * @module model/TownGovernmentSpending
 * @version 1.0.0
 */
class TownGovernmentSpending {
    /**
     * Constructs a new <code>TownGovernmentSpending</code>.
     * @alias module:model/TownGovernmentSpending
     */
    constructor() { 
        
        TownGovernmentSpending.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TownGovernmentSpending</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TownGovernmentSpending} obj Optional instance to populate.
     * @return {module:model/TownGovernmentSpending} The populated <code>TownGovernmentSpending</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TownGovernmentSpending();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('migration')) {
                obj['migration'] = ApiClient.convertToType(data['migration'], 'String');
            }
            if (data.hasOwnProperty('budget')) {
                obj['budget'] = ApiClient.convertToType(data['budget'], 'String');
            }
            if (data.hasOwnProperty('satisfaction')) {
                obj['satisfaction'] = ApiClient.convertToType(data['satisfaction'], 'String');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [TownCommonersIncomeItems]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TownGovernmentSpending</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TownGovernmentSpending</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['migration'] && !(typeof data['migration'] === 'string' || data['migration'] instanceof String)) {
            throw new Error("Expected the field `migration` to be a primitive type in the JSON string but got " + data['migration']);
        }
        // ensure the json data is a string
        if (data['budget'] && !(typeof data['budget'] === 'string' || data['budget'] instanceof String)) {
            throw new Error("Expected the field `budget` to be a primitive type in the JSON string but got " + data['budget']);
        }
        // ensure the json data is a string
        if (data['satisfaction'] && !(typeof data['satisfaction'] === 'string' || data['satisfaction'] instanceof String)) {
            throw new Error("Expected the field `satisfaction` to be a primitive type in the JSON string but got " + data['satisfaction']);
        }
        if (data['products']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['products'])) {
                throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
            }
            // validate the optional field `products` (array)
            for (const item of data['products']) {
                TownCommonersIncomeItems.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} name
 */
TownGovernmentSpending.prototype['name'] = undefined;

/**
 * @member {String} migration
 */
TownGovernmentSpending.prototype['migration'] = undefined;

/**
 * @member {String} budget
 */
TownGovernmentSpending.prototype['budget'] = undefined;

/**
 * @member {String} satisfaction
 */
TownGovernmentSpending.prototype['satisfaction'] = undefined;

/**
 * @member {Array.<module:model/TownCommonersIncomeItems>} products
 */
TownGovernmentSpending.prototype['products'] = undefined;






export default TownGovernmentSpending;

