/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MercatorioApi);
  }
}(this, function(expect, MercatorioApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MercatorioApi.BuildingConstruction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BuildingConstruction', function() {
    it('should create an instance of BuildingConstruction', function() {
      // uncomment below and update the code to test BuildingConstruction
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be.a(MercatorioApi.BuildingConstruction);
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be();
    });

    it('should have the property inventory (base name: "inventory")', function() {
      // uncomment below and update the code to test the property inventory
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be();
    });

    it('should have the property time (base name: "time")', function() {
      // uncomment below and update the code to test the property time
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be();
    });

    it('should have the property totalTime (base name: "total_time")', function() {
      // uncomment below and update the code to test the property totalTime
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be();
    });

    it('should have the property progress (base name: "progress")', function() {
      // uncomment below and update the code to test the property progress
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be();
    });

    it('should have the property stage (base name: "stage")', function() {
      // uncomment below and update the code to test the property stage
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be();
    });

    it('should have the property land (base name: "land")', function() {
      // uncomment below and update the code to test the property land
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be();
    });

    it('should have the property providerId (base name: "provider_id")', function() {
      // uncomment below and update the code to test the property providerId
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be();
    });

    it('should have the property settings (base name: "settings")', function() {
      // uncomment below and update the code to test the property settings
      //var instance = new MercatorioApi.BuildingConstruction();
      //expect(instance).to.be();
    });

  });

}));
