/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.mercatoriojs);
  }
}(this, function(expect, mercatoriojs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new mercatoriojs.BuildingPreviousOperation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BuildingPreviousOperation', function() {
    it('should create an instance of BuildingPreviousOperation', function() {
      // uncomment below and update the code to test BuildingPreviousOperation
      //var instance = new mercatoriojs.BuildingPreviousOperation();
      //expect(instance).to.be.a(mercatoriojs.BuildingPreviousOperation);
    });

    it('should have the property target (base name: "target")', function() {
      // uncomment below and update the code to test the property target
      //var instance = new mercatoriojs.BuildingPreviousOperation();
      //expect(instance).to.be();
    });

    it('should have the property production (base name: "production")', function() {
      // uncomment below and update the code to test the property production
      //var instance = new mercatoriojs.BuildingPreviousOperation();
      //expect(instance).to.be();
    });

    it('should have the property turns (base name: "turns")', function() {
      // uncomment below and update the code to test the property turns
      //var instance = new mercatoriojs.BuildingPreviousOperation();
      //expect(instance).to.be();
    });

  });

}));
