/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.mercatoriojs);
  }
}(this, function(expect, mercatoriojs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new mercatoriojs.InventoryAccount();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InventoryAccount', function() {
    it('should create an instance of InventoryAccount', function() {
      // uncomment below and update the code to test InventoryAccount
      //var instance = new mercatoriojs.InventoryAccount();
      //expect(instance).to.be.a(mercatoriojs.InventoryAccount);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new mercatoriojs.InventoryAccount();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new mercatoriojs.InventoryAccount();
      //expect(instance).to.be();
    });

    it('should have the property ownerId (base name: "owner_id")', function() {
      // uncomment below and update the code to test the property ownerId
      //var instance = new mercatoriojs.InventoryAccount();
      //expect(instance).to.be();
    });

    it('should have the property masterId (base name: "master_id")', function() {
      // uncomment below and update the code to test the property masterId
      //var instance = new mercatoriojs.InventoryAccount();
      //expect(instance).to.be();
    });

    it('should have the property sponsorId (base name: "sponsor_id")', function() {
      // uncomment below and update the code to test the property sponsorId
      //var instance = new mercatoriojs.InventoryAccount();
      //expect(instance).to.be();
    });

    it('should have the property assets (base name: "assets")', function() {
      // uncomment below and update the code to test the property assets
      //var instance = new mercatoriojs.InventoryAccount();
      //expect(instance).to.be();
    });

    it('should have the property ts (base name: "_ts")', function() {
      // uncomment below and update the code to test the property ts
      //var instance = new mercatoriojs.InventoryAccount();
      //expect(instance).to.be();
    });

  });

}));
