/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.mercatorio-js);
  }
}(this, function(expect, mercatorio-js) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new mercatorio-js.InventoryAssetsAlembics();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InventoryAssetsAlembics', function() {
    it('should create an instance of InventoryAssetsAlembics', function() {
      // uncomment below and update the code to test InventoryAssetsAlembics
      //var instance = new mercatorio-js.InventoryAssetsAlembics();
      //expect(instance).to.be.a(mercatorio-js.InventoryAssetsAlembics);
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instance = new mercatorio-js.InventoryAssetsAlembics();
      //expect(instance).to.be();
    });

    it('should have the property reserved (base name: "reserved")', function() {
      // uncomment below and update the code to test the property reserved
      //var instance = new mercatorio-js.InventoryAssetsAlembics();
      //expect(instance).to.be();
    });

    it('should have the property capacity (base name: "capacity")', function() {
      // uncomment below and update the code to test the property capacity
      //var instance = new mercatorio-js.InventoryAssetsAlembics();
      //expect(instance).to.be();
    });

    it('should have the property unitCost (base name: "unit_cost")', function() {
      // uncomment below and update the code to test the property unitCost
      //var instance = new mercatorio-js.InventoryAssetsAlembics();
      //expect(instance).to.be();
    });

  });

}));
