/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MercatorioApi);
  }
}(this, function(expect, MercatorioApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MercatorioApi.PlayerSettingsNotifications();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlayerSettingsNotifications', function() {
    it('should create an instance of PlayerSettingsNotifications', function() {
      // uncomment below and update the code to test PlayerSettingsNotifications
      //var instance = new MercatorioApi.PlayerSettingsNotifications();
      //expect(instance).to.be.a(MercatorioApi.PlayerSettingsNotifications);
    });

    it('should have the property discord (base name: "discord")', function() {
      // uncomment below and update the code to test the property discord
      //var instance = new MercatorioApi.PlayerSettingsNotifications();
      //expect(instance).to.be();
    });

    it('should have the property mutes (base name: "mutes")', function() {
      // uncomment below and update the code to test the property mutes
      //var instance = new MercatorioApi.PlayerSettingsNotifications();
      //expect(instance).to.be();
    });

  });

}));
