/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.mercatoriojs);
  }
}(this, function(expect, mercatoriojs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new mercatoriojs.TownSimple();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TownSimple', function() {
    it('should create an instance of TownSimple', function() {
      // uncomment below and update the code to test TownSimple
      //var instance = new mercatoriojs.TownSimple();
      //expect(instance).to.be.a(mercatoriojs.TownSimple);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new mercatoriojs.TownSimple();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new mercatoriojs.TownSimple();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new mercatoriojs.TownSimple();
      //expect(instance).to.be();
    });

    it('should have the property region (base name: "region")', function() {
      // uncomment below and update the code to test the property region
      //var instance = new mercatoriojs.TownSimple();
      //expect(instance).to.be();
    });

    it('should have the property capital (base name: "capital")', function() {
      // uncomment below and update the code to test the property capital
      //var instance = new mercatoriojs.TownSimple();
      //expect(instance).to.be();
    });

    it('should have the property satisfaction (base name: "satisfaction")', function() {
      // uncomment below and update the code to test the property satisfaction
      //var instance = new mercatoriojs.TownSimple();
      //expect(instance).to.be();
    });

    it('should have the property commoners (base name: "commoners")', function() {
      // uncomment below and update the code to test the property commoners
      //var instance = new mercatoriojs.TownSimple();
      //expect(instance).to.be();
    });

  });

}));
