/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.mercatoriojs);
  }
}(this, function(expect, mercatoriojs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new mercatoriojs.TownState();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TownState', function() {
    it('should create an instance of TownState', function() {
      // uncomment below and update the code to test TownState
      //var instance = new mercatoriojs.TownState();
      //expect(instance).to.be.a(mercatoriojs.TownState);
    });

    it('should have the property population (base name: "population")', function() {
      // uncomment below and update the code to test the property population
      //var instance = new mercatoriojs.TownState();
      //expect(instance).to.be();
    });

    it('should have the property totalPrestige (base name: "total_prestige")', function() {
      // uncomment below and update the code to test the property totalPrestige
      //var instance = new mercatoriojs.TownState();
      //expect(instance).to.be();
    });

    it('should have the property totalHealth (base name: "total_health")', function() {
      // uncomment below and update the code to test the property totalHealth
      //var instance = new mercatoriojs.TownState();
      //expect(instance).to.be();
    });

  });

}));
