/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.mercatoriojs);
  }
}(this, function(expect, mercatoriojs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new mercatoriojs.Town();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Town', function() {
    it('should create an instance of Town', function() {
      // uncomment below and update the code to test Town
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be.a(mercatoriojs.Town);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property region (base name: "region")', function() {
      // uncomment below and update the code to test the property region
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property capitalId (base name: "capital_id")', function() {
      // uncomment below and update the code to test the property capitalId
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property centerIds (base name: "center_ids")', function() {
      // uncomment below and update the code to test the property centerIds
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property domain (base name: "domain")', function() {
      // uncomment below and update the code to test the property domain
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property householdIds (base name: "household_ids")', function() {
      // uncomment below and update the code to test the property householdIds
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property commoners (base name: "commoners")', function() {
      // uncomment below and update the code to test the property commoners
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property government (base name: "government")', function() {
      // uncomment below and update the code to test the property government
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property church (base name: "church")', function() {
      // uncomment below and update the code to test the property church
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property navigationZones (base name: "navigation_zones")', function() {
      // uncomment below and update the code to test the property navigationZones
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property culture (base name: "culture")', function() {
      // uncomment below and update the code to test the property culture
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

    it('should have the property ts (base name: "_ts")', function() {
      // uncomment below and update the code to test the property ts
      //var instance = new mercatoriojs.Town();
      //expect(instance).to.be();
    });

  });

}));
