/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.mercatoriojs);
  }
}(this, function(expect, mercatoriojs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new mercatoriojs.TownNavigationZones();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TownNavigationZones', function() {
    it('should create an instance of TownNavigationZones', function() {
      // uncomment below and update the code to test TownNavigationZones
      //var instance = new mercatoriojs.TownNavigationZones();
      //expect(instance).to.be.a(mercatoriojs.TownNavigationZones);
    });

    it('should have the property navigationZoneID1 (base name: "NavigationZoneID1")', function() {
      // uncomment below and update the code to test the property navigationZoneID1
      //var instance = new mercatoriojs.TownNavigationZones();
      //expect(instance).to.be();
    });

    it('should have the property navigationZoneID2 (base name: "NavigationZoneID2")', function() {
      // uncomment below and update the code to test the property navigationZoneID2
      //var instance = new mercatoriojs.TownNavigationZones();
      //expect(instance).to.be();
    });

    it('should have the property navigationZoneID3 (base name: "NavigationZoneID3")', function() {
      // uncomment below and update the code to test the property navigationZoneID3
      //var instance = new mercatoriojs.TownNavigationZones();
      //expect(instance).to.be();
    });

  });

}));
