/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.mercatoriojs);
  }
}(this, function(expect, mercatoriojs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new mercatoriojs.TownGovernmentTaxesCollected();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TownGovernmentTaxesCollected', function() {
    it('should create an instance of TownGovernmentTaxesCollected', function() {
      // uncomment below and update the code to test TownGovernmentTaxesCollected
      //var instance = new mercatoriojs.TownGovernmentTaxesCollected();
      //expect(instance).to.be.a(mercatoriojs.TownGovernmentTaxesCollected);
    });

    it('should have the property payments (base name: "payments")', function() {
      // uncomment below and update the code to test the property payments
      //var instance = new mercatoriojs.TownGovernmentTaxesCollected();
      //expect(instance).to.be();
    });

    it('should have the property landTax (base name: "land_tax")', function() {
      // uncomment below and update the code to test the property landTax
      //var instance = new mercatoriojs.TownGovernmentTaxesCollected();
      //expect(instance).to.be();
    });

    it('should have the property structureTax (base name: "structure_tax")', function() {
      // uncomment below and update the code to test the property structureTax
      //var instance = new mercatoriojs.TownGovernmentTaxesCollected();
      //expect(instance).to.be();
    });

    it('should have the property deliveryFees (base name: "delivery_fees")', function() {
      // uncomment below and update the code to test the property deliveryFees
      //var instance = new mercatoriojs.TownGovernmentTaxesCollected();
      //expect(instance).to.be();
    });

    it('should have the property transportFees (base name: "transport_fees")', function() {
      // uncomment below and update the code to test the property transportFees
      //var instance = new mercatoriojs.TownGovernmentTaxesCollected();
      //expect(instance).to.be();
    });

  });

}));
