/**
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MercatorioApi);
  }
}(this, function(expect, MercatorioApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MercatorioApi.WorkerSkills();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WorkerSkills', function() {
    it('should create an instance of WorkerSkills', function() {
      // uncomment below and update the code to test WorkerSkills
      //var instance = new MercatorioApi.WorkerSkills();
      //expect(instance).to.be.a(MercatorioApi.WorkerSkills);
    });

    it('should have the property nutrition (base name: "nutrition")', function() {
      // uncomment below and update the code to test the property nutrition
      //var instance = new MercatorioApi.WorkerSkills();
      //expect(instance).to.be();
    });

    it('should have the property textile (base name: "textile")', function() {
      // uncomment below and update the code to test the property textile
      //var instance = new MercatorioApi.WorkerSkills();
      //expect(instance).to.be();
    });

    it('should have the property crafting (base name: "crafting")', function() {
      // uncomment below and update the code to test the property crafting
      //var instance = new MercatorioApi.WorkerSkills();
      //expect(instance).to.be();
    });

    it('should have the property forging (base name: "forging")', function() {
      // uncomment below and update the code to test the property forging
      //var instance = new MercatorioApi.WorkerSkills();
      //expect(instance).to.be();
    });

    it('should have the property weaponry (base name: "weaponry")', function() {
      // uncomment below and update the code to test the property weaponry
      //var instance = new MercatorioApi.WorkerSkills();
      //expect(instance).to.be();
    });

    it('should have the property maritime (base name: "maritime")', function() {
      // uncomment below and update the code to test the property maritime
      //var instance = new MercatorioApi.WorkerSkills();
      //expect(instance).to.be();
    });

    it('should have the property mercantile (base name: "mercantile")', function() {
      // uncomment below and update the code to test the property mercantile
      //var instance = new MercatorioApi.WorkerSkills();
      //expect(instance).to.be();
    });

  });

}));
