/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CommonersTownState
 */
public class CommonersTownStateTest {
    private final CommonersTownState model = new CommonersTownState();

    /**
     * Model tests for CommonersTownState
     */
    @Test
    public void testCommonersTownState() {
        // TODO: test CommonersTownState
    }

    /**
     * Test the property 'migration'
     */
    @Test
    public void migrationTest() {
        // TODO: test migration
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'prestige'
     */
    @Test
    public void prestigeTest() {
        // TODO: test prestige
    }

    /**
     * Test the property 'health'
     */
    @Test
    public void healthTest() {
        // TODO: test health
    }

}
