/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HouseholdCaps
 */
public class HouseholdCapsTest {
    private final HouseholdCaps model = new HouseholdCaps();

    /**
     * Model tests for HouseholdCaps
     */
    @Test
    public void testHouseholdCaps() {
        // TODO: test HouseholdCaps
    }

    /**
     * Test the property 'transports'
     */
    @Test
    public void transportsTest() {
        // TODO: test transports
    }

    /**
     * Test the property 'regularManagement'
     */
    @Test
    public void regularManagementTest() {
        // TODO: test regularManagement
    }

    /**
     * Test the property 'prestigeManagement'
     */
    @Test
    public void prestigeManagementTest() {
        // TODO: test prestigeManagement
    }

    /**
     * Test the property 'tenants'
     */
    @Test
    public void tenantsTest() {
        // TODO: test tenants
    }

    /**
     * Test the property 'apprentices'
     */
    @Test
    public void apprenticesTest() {
        // TODO: test apprentices
    }

}
