/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.HouseholdCaps;
import org.openapitools.client.model.HouseholdSustenance;
import org.openapitools.client.model.PrestigeImpact;
import org.openapitools.client.model.Specialization;
import org.openapitools.client.model.Worker;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Household
 */
public class HouseholdTest {
    private final Household model = new Household();

    /**
     * Model tests for Household
     */
    @Test
    public void testHousehold() {
        // TODO: test Household
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'townId'
     */
    @Test
    public void townIdTest() {
        // TODO: test townId
    }

    /**
     * Test the property 'portrait'
     */
    @Test
    public void portraitTest() {
        // TODO: test portrait
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'businessIds'
     */
    @Test
    public void businessIdsTest() {
        // TODO: test businessIds
    }

    /**
     * Test the property 'prestige'
     */
    @Test
    public void prestigeTest() {
        // TODO: test prestige
    }

    /**
     * Test the property 'prestigeImpacts'
     */
    @Test
    public void prestigeImpactsTest() {
        // TODO: test prestigeImpacts
    }

    /**
     * Test the property 'legacy'
     */
    @Test
    public void legacyTest() {
        // TODO: test legacy
    }

    /**
     * Test the property 'workers'
     */
    @Test
    public void workersTest() {
        // TODO: test workers
    }

    /**
     * Test the property 'specialization'
     */
    @Test
    public void specializationTest() {
        // TODO: test specialization
    }

    /**
     * Test the property 'operations'
     */
    @Test
    public void operationsTest() {
        // TODO: test operations
    }

    /**
     * Test the property 'caps'
     */
    @Test
    public void capsTest() {
        // TODO: test caps
    }

    /**
     * Test the property 'sustenance'
     */
    @Test
    public void sustenanceTest() {
        // TODO: test sustenance
    }

}
