/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.Holdings;
import org.openapitools.client.model.InventoryAccount;
import org.openapitools.client.model.InventoryFlows;
import org.openapitools.client.model.InventoryPastFlows;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Inventory
 */
public class InventoryTest {
    private final Inventory model = new Inventory();

    /**
     * Model tests for Inventory
     */
    @Test
    public void testInventory() {
        // TODO: test Inventory
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'capacity'
     */
    @Test
    public void capacityTest() {
        // TODO: test capacity
    }

    /**
     * Test the property 'reserved'
     */
    @Test
    public void reservedTest() {
        // TODO: test reserved
    }

    /**
     * Test the property 'used'
     */
    @Test
    public void usedTest() {
        // TODO: test used
    }

    /**
     * Test the property 'holdings'
     */
    @Test
    public void holdingsTest() {
        // TODO: test holdings
    }

    /**
     * Test the property 'flows'
     */
    @Test
    public void flowsTest() {
        // TODO: test flows
    }

    /**
     * Test the property 'previousFlows'
     */
    @Test
    public void previousFlowsTest() {
        // TODO: test previousFlows
    }

}
