/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProductFlow;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InventoryFlowsAlembics
 */
public class InventoryFlowsAlembicsTest {
    private final InventoryFlowsAlembics model = new InventoryFlowsAlembics();

    /**
     * Model tests for InventoryFlowsAlembics
     */
    @Test
    public void testInventoryFlowsAlembics() {
        // TODO: test InventoryFlowsAlembics
    }

    /**
     * Test the property 'projection'
     */
    @Test
    public void projectionTest() {
        // TODO: test projection
    }

}
