/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProductFlow;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InventoryPastFlows
 */
public class InventoryPastFlowsTest {
    private final InventoryPastFlows model = new InventoryPastFlows();

    /**
     * Model tests for InventoryPastFlows
     */
    @Test
    public void testInventoryPastFlows() {
        // TODO: test InventoryPastFlows
    }

    /**
     * Test the property 'alembics'
     */
    @Test
    public void alembicsTest() {
        // TODO: test alembics
    }

    /**
     * Test the property 'arms'
     */
    @Test
    public void armsTest() {
        // TODO: test arms
    }

    /**
     * Test the property 'axes'
     */
    @Test
    public void axesTest() {
        // TODO: test axes
    }

    /**
     * Test the property 'beer'
     */
    @Test
    public void beerTest() {
        // TODO: test beer
    }

    /**
     * Test the property 'bellows'
     */
    @Test
    public void bellowsTest() {
        // TODO: test bellows
    }

    /**
     * Test the property 'bells'
     */
    @Test
    public void bellsTest() {
        // TODO: test bells
    }

    /**
     * Test the property 'belts'
     */
    @Test
    public void beltsTest() {
        // TODO: test belts
    }

    /**
     * Test the property 'blades'
     */
    @Test
    public void bladesTest() {
        // TODO: test blades
    }

    /**
     * Test the property 'books'
     */
    @Test
    public void booksTest() {
        // TODO: test books
    }

    /**
     * Test the property 'bread'
     */
    @Test
    public void breadTest() {
        // TODO: test bread
    }

    /**
     * Test the property 'bronzeIngots'
     */
    @Test
    public void bronzeIngotsTest() {
        // TODO: test bronzeIngots
    }

    /**
     * Test the property 'butter'
     */
    @Test
    public void butterTest() {
        // TODO: test butter
    }

    /**
     * Test the property 'candles'
     */
    @Test
    public void candlesTest() {
        // TODO: test candles
    }

    /**
     * Test the property 'carting'
     */
    @Test
    public void cartingTest() {
        // TODO: test carting
    }

    /**
     * Test the property 'casks'
     */
    @Test
    public void casksTest() {
        // TODO: test casks
    }

    /**
     * Test the property 'cattle'
     */
    @Test
    public void cattleTest() {
        // TODO: test cattle
    }

    /**
     * Test the property 'charcoal'
     */
    @Test
    public void charcoalTest() {
        // TODO: test charcoal
    }

    /**
     * Test the property 'cheese'
     */
    @Test
    public void cheeseTest() {
        // TODO: test cheese
    }

    /**
     * Test the property 'chisels'
     */
    @Test
    public void chiselsTest() {
        // TODO: test chisels
    }

    /**
     * Test the property 'clay'
     */
    @Test
    public void clayTest() {
        // TODO: test clay
    }

    /**
     * Test the property 'cloth'
     */
    @Test
    public void clothTest() {
        // TODO: test cloth
    }

    /**
     * Test the property 'coats'
     */
    @Test
    public void coatsTest() {
        // TODO: test coats
    }

    /**
     * Test the property 'cookware'
     */
    @Test
    public void cookwareTest() {
        // TODO: test cookware
    }

    /**
     * Test the property 'copperIngots'
     */
    @Test
    public void copperIngotsTest() {
        // TODO: test copperIngots
    }

    /**
     * Test the property 'copperOre'
     */
    @Test
    public void copperOreTest() {
        // TODO: test copperOre
    }

    /**
     * Test the property 'curedFish'
     */
    @Test
    public void curedFishTest() {
        // TODO: test curedFish
    }

    /**
     * Test the property 'curedMeat'
     */
    @Test
    public void curedMeatTest() {
        // TODO: test curedMeat
    }

    /**
     * Test the property 'dye'
     */
    @Test
    public void dyeTest() {
        // TODO: test dye
    }

    /**
     * Test the property 'dyedCloth'
     */
    @Test
    public void dyedClothTest() {
        // TODO: test dyedCloth
    }

    /**
     * Test the property 'dyedYarn'
     */
    @Test
    public void dyedYarnTest() {
        // TODO: test dyedYarn
    }

    /**
     * Test the property 'firewood'
     */
    @Test
    public void firewoodTest() {
        // TODO: test firewood
    }

    /**
     * Test the property 'fish'
     */
    @Test
    public void fishTest() {
        // TODO: test fish
    }

    /**
     * Test the property 'flaxFibres'
     */
    @Test
    public void flaxFibresTest() {
        // TODO: test flaxFibres
    }

    /**
     * Test the property 'flaxPlants'
     */
    @Test
    public void flaxPlantsTest() {
        // TODO: test flaxPlants
    }

    /**
     * Test the property 'fleece'
     */
    @Test
    public void fleeceTest() {
        // TODO: test fleece
    }

    /**
     * Test the property 'flour'
     */
    @Test
    public void flourTest() {
        // TODO: test flour
    }

    /**
     * Test the property 'furniture'
     */
    @Test
    public void furnitureTest() {
        // TODO: test furniture
    }

    /**
     * Test the property 'garments'
     */
    @Test
    public void garmentsTest() {
        // TODO: test garments
    }

    /**
     * Test the property 'gears'
     */
    @Test
    public void gearsTest() {
        // TODO: test gears
    }

    /**
     * Test the property 'glass'
     */
    @Test
    public void glassTest() {
        // TODO: test glass
    }

    /**
     * Test the property 'glassware'
     */
    @Test
    public void glasswareTest() {
        // TODO: test glassware
    }

    /**
     * Test the property 'goldBars'
     */
    @Test
    public void goldBarsTest() {
        // TODO: test goldBars
    }

    /**
     * Test the property 'goldOre'
     */
    @Test
    public void goldOreTest() {
        // TODO: test goldOre
    }

    /**
     * Test the property 'grain'
     */
    @Test
    public void grainTest() {
        // TODO: test grain
    }

    /**
     * Test the property 'grindstones'
     */
    @Test
    public void grindstonesTest() {
        // TODO: test grindstones
    }

    /**
     * Test the property 'ham'
     */
    @Test
    public void hamTest() {
        // TODO: test ham
    }

    /**
     * Test the property 'harnesses'
     */
    @Test
    public void harnessesTest() {
        // TODO: test harnesses
    }

    /**
     * Test the property 'herbs'
     */
    @Test
    public void herbsTest() {
        // TODO: test herbs
    }

    /**
     * Test the property 'hides'
     */
    @Test
    public void hidesTest() {
        // TODO: test hides
    }

    /**
     * Test the property 'hinges'
     */
    @Test
    public void hingesTest() {
        // TODO: test hinges
    }

    /**
     * Test the property 'honey'
     */
    @Test
    public void honeyTest() {
        // TODO: test honey
    }

    /**
     * Test the property 'hopBeer'
     */
    @Test
    public void hopBeerTest() {
        // TODO: test hopBeer
    }

    /**
     * Test the property 'ironOre'
     */
    @Test
    public void ironOreTest() {
        // TODO: test ironOre
    }

    /**
     * Test the property 'jewellery'
     */
    @Test
    public void jewelleryTest() {
        // TODO: test jewellery
    }

    /**
     * Test the property 'labour'
     */
    @Test
    public void labourTest() {
        // TODO: test labour
    }

    /**
     * Test the property 'lathes'
     */
    @Test
    public void lathesTest() {
        // TODO: test lathes
    }

    /**
     * Test the property 'leadBars'
     */
    @Test
    public void leadBarsTest() {
        // TODO: test leadBars
    }

    /**
     * Test the property 'leadOre'
     */
    @Test
    public void leadOreTest() {
        // TODO: test leadOre
    }

    /**
     * Test the property 'leather'
     */
    @Test
    public void leatherTest() {
        // TODO: test leather
    }

    /**
     * Test the property 'lightArmour'
     */
    @Test
    public void lightArmourTest() {
        // TODO: test lightArmour
    }

    /**
     * Test the property 'limestone'
     */
    @Test
    public void limestoneTest() {
        // TODO: test limestone
    }

    /**
     * Test the property 'lodging'
     */
    @Test
    public void lodgingTest() {
        // TODO: test lodging
    }

    /**
     * Test the property 'logs'
     */
    @Test
    public void logsTest() {
        // TODO: test logs
    }

    /**
     * Test the property 'looms'
     */
    @Test
    public void loomsTest() {
        // TODO: test looms
    }

    /**
     * Test the property 'malt'
     */
    @Test
    public void maltTest() {
        // TODO: test malt
    }

    /**
     * Test the property 'manure'
     */
    @Test
    public void manureTest() {
        // TODO: test manure
    }

    /**
     * Test the property 'meat'
     */
    @Test
    public void meatTest() {
        // TODO: test meat
    }

    /**
     * Test the property 'medicine'
     */
    @Test
    public void medicineTest() {
        // TODO: test medicine
    }

    /**
     * Test the property 'milk'
     */
    @Test
    public void milkTest() {
        // TODO: test milk
    }

    /**
     * Test the property 'mouldboards'
     */
    @Test
    public void mouldboardsTest() {
        // TODO: test mouldboards
    }

    /**
     * Test the property 'nails'
     */
    @Test
    public void nailsTest() {
        // TODO: test nails
    }

    /**
     * Test the property 'nets'
     */
    @Test
    public void netsTest() {
        // TODO: test nets
    }

    /**
     * Test the property 'oxPower'
     */
    @Test
    public void oxPowerTest() {
        // TODO: test oxPower
    }

    /**
     * Test the property 'paper'
     */
    @Test
    public void paperTest() {
        // TODO: test paper
    }

    /**
     * Test the property 'pasties'
     */
    @Test
    public void pastiesTest() {
        // TODO: test pasties
    }

    /**
     * Test the property 'pickaxes'
     */
    @Test
    public void pickaxesTest() {
        // TODO: test pickaxes
    }

    /**
     * Test the property 'pies'
     */
    @Test
    public void piesTest() {
        // TODO: test pies
    }

    /**
     * Test the property 'plateArmour'
     */
    @Test
    public void plateArmourTest() {
        // TODO: test plateArmour
    }

    /**
     * Test the property 'ploughs'
     */
    @Test
    public void ploughsTest() {
        // TODO: test ploughs
    }

    /**
     * Test the property 'premiumArmour'
     */
    @Test
    public void premiumArmourTest() {
        // TODO: test premiumArmour
    }

    /**
     * Test the property 'premiumAxes'
     */
    @Test
    public void premiumAxesTest() {
        // TODO: test premiumAxes
    }

    /**
     * Test the property 'premiumCheese'
     */
    @Test
    public void premiumCheeseTest() {
        // TODO: test premiumCheese
    }

    /**
     * Test the property 'premiumCloth'
     */
    @Test
    public void premiumClothTest() {
        // TODO: test premiumCloth
    }

    /**
     * Test the property 'premiumDye'
     */
    @Test
    public void premiumDyeTest() {
        // TODO: test premiumDye
    }

    /**
     * Test the property 'premiumGarments'
     */
    @Test
    public void premiumGarmentsTest() {
        // TODO: test premiumGarments
    }

    /**
     * Test the property 'premiumGlassware'
     */
    @Test
    public void premiumGlasswareTest() {
        // TODO: test premiumGlassware
    }

    /**
     * Test the property 'premiumHam'
     */
    @Test
    public void premiumHamTest() {
        // TODO: test premiumHam
    }

    /**
     * Test the property 'premiumSails'
     */
    @Test
    public void premiumSailsTest() {
        // TODO: test premiumSails
    }

    /**
     * Test the property 'premiumSteel'
     */
    @Test
    public void premiumSteelTest() {
        // TODO: test premiumSteel
    }

    /**
     * Test the property 'premiumSwords'
     */
    @Test
    public void premiumSwordsTest() {
        // TODO: test premiumSwords
    }

    /**
     * Test the property 'protection'
     */
    @Test
    public void protectionTest() {
        // TODO: test protection
    }

    /**
     * Test the property 'rawCloth'
     */
    @Test
    public void rawClothTest() {
        // TODO: test rawCloth
    }

    /**
     * Test the property 'resin'
     */
    @Test
    public void resinTest() {
        // TODO: test resin
    }

    /**
     * Test the property 'rope'
     */
    @Test
    public void ropeTest() {
        // TODO: test rope
    }

    /**
     * Test the property 'sails'
     */
    @Test
    public void sailsTest() {
        // TODO: test sails
    }

    /**
     * Test the property 'salt'
     */
    @Test
    public void saltTest() {
        // TODO: test salt
    }

    /**
     * Test the property 'sculptures'
     */
    @Test
    public void sculpturesTest() {
        // TODO: test sculptures
    }

    /**
     * Test the property 'scythes'
     */
    @Test
    public void scythesTest() {
        // TODO: test scythes
    }

    /**
     * Test the property 'silverBars'
     */
    @Test
    public void silverBarsTest() {
        // TODO: test silverBars
    }

    /**
     * Test the property 'silverOre'
     */
    @Test
    public void silverOreTest() {
        // TODO: test silverOre
    }

    /**
     * Test the property 'slakedLime'
     */
    @Test
    public void slakedLimeTest() {
        // TODO: test slakedLime
    }

    /**
     * Test the property 'spinningWheels'
     */
    @Test
    public void spinningWheelsTest() {
        // TODO: test spinningWheels
    }

    /**
     * Test the property 'spirits'
     */
    @Test
    public void spiritsTest() {
        // TODO: test spirits
    }

    /**
     * Test the property 'steelIngots'
     */
    @Test
    public void steelIngotsTest() {
        // TODO: test steelIngots
    }

    /**
     * Test the property 'stockfish'
     */
    @Test
    public void stockfishTest() {
        // TODO: test stockfish
    }

    /**
     * Test the property 'swords'
     */
    @Test
    public void swordsTest() {
        // TODO: test swords
    }

    /**
     * Test the property 'tackles'
     */
    @Test
    public void tacklesTest() {
        // TODO: test tackles
    }

    /**
     * Test the property 'tapestries'
     */
    @Test
    public void tapestriesTest() {
        // TODO: test tapestries
    }

    /**
     * Test the property 'tar'
     */
    @Test
    public void tarTest() {
        // TODO: test tar
    }

    /**
     * Test the property 'thread'
     */
    @Test
    public void threadTest() {
        // TODO: test thread
    }

    /**
     * Test the property 'tiles'
     */
    @Test
    public void tilesTest() {
        // TODO: test tiles
    }

    /**
     * Test the property 'timber'
     */
    @Test
    public void timberTest() {
        // TODO: test timber
    }

    /**
     * Test the property 'tinIngots'
     */
    @Test
    public void tinIngotsTest() {
        // TODO: test tinIngots
    }

    /**
     * Test the property 'tinOre'
     */
    @Test
    public void tinOreTest() {
        // TODO: test tinOre
    }

    /**
     * Test the property 'tools'
     */
    @Test
    public void toolsTest() {
        // TODO: test tools
    }

    /**
     * Test the property 'wax'
     */
    @Test
    public void waxTest() {
        // TODO: test wax
    }

    /**
     * Test the property 'wheels'
     */
    @Test
    public void wheelsTest() {
        // TODO: test wheels
    }

    /**
     * Test the property 'windows'
     */
    @Test
    public void windowsTest() {
        // TODO: test windows
    }

    /**
     * Test the property 'wine'
     */
    @Test
    public void wineTest() {
        // TODO: test wine
    }

    /**
     * Test the property 'wool'
     */
    @Test
    public void woolTest() {
        // TODO: test wool
    }

    /**
     * Test the property 'wroughtIron'
     */
    @Test
    public void wroughtIronTest() {
        // TODO: test wroughtIron
    }

    /**
     * Test the property 'yarn'
     */
    @Test
    public void yarnTest() {
        // TODO: test yarn
    }

}
