/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlayerSettingsNotifications
 */
public class PlayerSettingsNotificationsTest {
    private final PlayerSettingsNotifications model = new PlayerSettingsNotifications();

    /**
     * Model tests for PlayerSettingsNotifications
     */
    @Test
    public void testPlayerSettingsNotifications() {
        // TODO: test PlayerSettingsNotifications
    }

    /**
     * Test the property 'discord'
     */
    @Test
    public void discordTest() {
        // TODO: test discord
    }

    /**
     * Test the property 'mutes'
     */
    @Test
    public void mutesTest() {
        // TODO: test mutes
    }

}
