/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.PlayerSettingsEmail;
import org.openapitools.client.model.PlayerSettingsNotifications;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlayerSettings
 */
public class PlayerSettingsTest {
    private final PlayerSettings model = new PlayerSettings();

    /**
     * Model tests for PlayerSettings
     */
    @Test
    public void testPlayerSettings() {
        // TODO: test PlayerSettings
    }

    /**
     * Test the property 'soundVolume'
     */
    @Test
    public void soundVolumeTest() {
        // TODO: test soundVolume
    }

    /**
     * Test the property 'notifications'
     */
    @Test
    public void notificationsTest() {
        // TODO: test notifications
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

}
