/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PrestigeImpact
 */
public class PrestigeImpactTest {
    private final PrestigeImpact model = new PrestigeImpact();

    /**
     * Model tests for PrestigeImpact
     */
    @Test
    public void testPrestigeImpact() {
        // TODO: test PrestigeImpact
    }

    /**
     * Test the property 'factor'
     */
    @Test
    public void factorTest() {
        // TODO: test factor
    }

    /**
     * Test the property 'impact'
     */
    @Test
    public void impactTest() {
        // TODO: test impact
    }

}
