/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Location;
import org.openapitools.client.model.TownChurch;
import org.openapitools.client.model.TownCommoners;
import org.openapitools.client.model.TownCulture;
import org.openapitools.client.model.TownDomain;
import org.openapitools.client.model.TownGovernment;
import org.openapitools.client.model.TownNavigationZones;
import org.openapitools.client.model.TownState;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Town
 */
public class TownTest {
    private final Town model = new Town();

    /**
     * Model tests for Town
     */
    @Test
    public void testTown() {
        // TODO: test Town
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'capitalId'
     */
    @Test
    public void capitalIdTest() {
        // TODO: test capitalId
    }

    /**
     * Test the property 'centerIds'
     */
    @Test
    public void centerIdsTest() {
        // TODO: test centerIds
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'householdIds'
     */
    @Test
    public void householdIdsTest() {
        // TODO: test householdIds
    }

    /**
     * Test the property 'commoners'
     */
    @Test
    public void commonersTest() {
        // TODO: test commoners
    }

    /**
     * Test the property 'government'
     */
    @Test
    public void governmentTest() {
        // TODO: test government
    }

    /**
     * Test the property 'church'
     */
    @Test
    public void churchTest() {
        // TODO: test church
    }

    /**
     * Test the property 'navigationZones'
     */
    @Test
    public void navigationZonesTest() {
        // TODO: test navigationZones
    }

    /**
     * Test the property 'culture'
     */
    @Test
    public void cultureTest() {
        // TODO: test culture
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'ts'
     */
    @Test
    public void tsTest() {
        // TODO: test ts
    }

}
