/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.TownCommonersIncomeItems;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TownCommonersIncome
 */
public class TownCommonersIncomeTest {
    private final TownCommonersIncome model = new TownCommonersIncome();

    /**
     * Model tests for TownCommonersIncome
     */
    @Test
    public void testTownCommonersIncome() {
        // TODO: test TownCommonersIncome
    }

    /**
     * Test the property 'migration'
     */
    @Test
    public void migrationTest() {
        // TODO: test migration
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

}
