/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.TownCommonersIncomeItems;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TownCommonersSpending
 */
public class TownCommonersSpendingTest {
    private final TownCommonersSpending model = new TownCommonersSpending();

    /**
     * Model tests for TownCommonersSpending
     */
    @Test
    public void testTownCommonersSpending() {
        // TODO: test TownCommonersSpending
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'budget'
     */
    @Test
    public void budgetTest() {
        // TODO: test budget
    }

    /**
     * Test the property 'satisfaction'
     */
    @Test
    public void satisfactionTest() {
        // TODO: test satisfaction
    }

    /**
     * Test the property 'products'
     */
    @Test
    public void productsTest() {
        // TODO: test products
    }

}
