/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DomainPlot;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TownDomain
 */
public class TownDomainTest {
    private final TownDomain model = new TownDomain();

    /**
     * Model tests for TownDomain
     */
    @Test
    public void testTownDomain() {
        // TODO: test TownDomain
    }

    /**
     * Test the property 'plotID1'
     */
    @Test
    public void plotID1Test() {
        // TODO: test plotID1
    }

    /**
     * Test the property 'plotID2'
     */
    @Test
    public void plotID2Test() {
        // TODO: test plotID2
    }

    /**
     * Test the property 'plotID3'
     */
    @Test
    public void plotID3Test() {
        // TODO: test plotID3
    }

    /**
     * Test the property 'plotID4'
     */
    @Test
    public void plotID4Test() {
        // TODO: test plotID4
    }

    /**
     * Test the property 'plotID5'
     */
    @Test
    public void plotID5Test() {
        // TODO: test plotID5
    }

}
