/*
 * Mercatorio API
 * API to interact with the game of Mercatorio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TownCommonersIncomeItems
 */
public class TownCommonersIncomeItemsTest {
    private final TownCommonersIncomeItems model = new TownCommonersIncomeItems();

    /**
     * Model tests for TownCommonersIncomeItems
     */
    @Test
    public void testTownCommonersIncomeItems() {
        // TODO: test TownCommonersIncomeItems
    }

    /**
     * Test the property 'product'
     */
    @Test
    public void productTest() {
        // TODO: test product
    }

    /**
     * Test the property 'bonus'
     */
    @Test
    public void bonusTest() {
        // TODO: test bonus
    }

    /**
     * Test the property 'desire'
     */
    @Test
    public void desireTest() {
        // TODO: test desire
    }

    /**
     * Test the property 'request'
     */
    @Test
    public void requestTest() {
        // TODO: test request
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'budget'
     */
    @Test
    public void budgetTest() {
        // TODO: test budget
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

}
